// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - BankAccount class
	/// </summary>
	public partial class BKBankAccount
	{


		/// <summary>
		/// BankAccountNumber property
		/// </summary>
		[XmlAttribute("BankAccountNumber", DataType = "string")]
		public String BankAccountNumber { get; set; }



		/// <summary>
		/// BankAccountName property
		/// </summary>
		[XmlAttribute("BankAccountName", DataType = "string")]
		public String BankAccountName { get; set; }



		/// <summary>
		/// BankAccountPassword property
		/// </summary>
		[XmlAttribute("BankAccountPassword", DataType = "string")]
		public String BankAccountPassword { get; set; }



		/// <summary>
		/// ContraAccountCode property
		/// </summary>
		[XmlAttribute("ContraAccountCode", DataType = "string")]
		public String ContraAccountCode { get; set; }



		/// <summary>
		/// CurrentBalance property
		/// </summary>
		[XmlAttribute("CurrentBalance", DataType = "long")]
		public Int64 CurrentBalance { get; set; }



		/// <summary>
		/// ApplyMasterMemorisedEntries property
		/// </summary>
		[XmlAttribute("ApplyMasterMemorisedEntries", DataType = "boolean")]
		public bool ApplyMasterMemorisedEntries { get; set; }



		/// <summary>
		/// AccountType property
		/// </summary>
		[XmlAttribute("AccountType", DataType = "unsignedByte")]
		public byte AccountType { get; set; }



		/// <summary>
		/// ColumnOrder property
		/// </summary>
		[XmlArray("ColumnOrders"),XmlArrayItem("ColumnOrder", DataType = "unsignedByte")]
		public byte[] ColumnOrder { get; set; }


		/// <summary>
		/// ColumnWidth property
		/// </summary>
		[XmlArray("ColumnWidths"),XmlArrayItem("ColumnWidth", DataType = "int")]
		public Int32[] ColumnWidth { get; set; }


		/// <summary>
		/// PreferredView property
		/// </summary>
		[XmlAttribute("PreferredView", DataType = "unsignedByte")]
		public byte PreferredView { get; set; }



		/// <summary>
		/// HighestBankLinkID property
		/// </summary>
		[XmlAttribute("HighestBankLinkID", DataType = "int")]
		public Int32 HighestBankLinkID { get; set; }



		/// <summary>
		/// HighestLRN property
		/// </summary>
		[XmlAttribute("HighestLRN", DataType = "int")]
		public Int32 HighestLRN { get; set; }



		/// <summary>
		/// ColumnisHidden property
		/// </summary>
		[XmlArray("ColumnisHiddens"),XmlArrayItem("ColumnisHidden", DataType = "boolean")]
		public bool[] ColumnisHidden { get; set; }


		/// <summary>
		/// AccountExpiryDate property
		/// </summary>
		[XmlAttribute("AccountExpiryDate", DataType = "int")]
		public Int32 AccountExpiryDate { get; set; }



		/// <summary>
		/// HighestMatchedItemID property
		/// </summary>
		[XmlAttribute("HighestMatchedItemID", DataType = "int")]
		public Int32 HighestMatchedItemID { get; set; }



		/// <summary>
		/// NotesAlwaysVisible property
		/// </summary>
		[XmlAttribute("NotesAlwaysVisible", DataType = "boolean")]
		public bool NotesAlwaysVisible { get; set; }



		/// <summary>
		/// NotesHeight property
		/// </summary>
		[XmlAttribute("NotesHeight", DataType = "int")]
		public Int32 NotesHeight { get; set; }



		/// <summary>
		/// LastECodingTransactionUID property
		/// </summary>
		[XmlAttribute("LastECodingTransactionUID", DataType = "int")]
		public Int32 LastECodingTransactionUID { get; set; }



		/// <summary>
		/// ColumnIsNotEditable property
		/// </summary>
		[XmlArray("ColumnIsNotEditables"),XmlArrayItem("ColumnIsNotEditable", DataType = "boolean")]
		public bool[] ColumnIsNotEditable { get; set; }


		/// <summary>
		/// ExtendExpiryDate property
		/// </summary>
		[XmlAttribute("ExtendExpiryDate", DataType = "boolean")]
		public bool ExtendExpiryDate { get; set; }



		/// <summary>
		/// IsAManualAccount property
		/// </summary>
		[XmlAttribute("IsAManualAccount", DataType = "boolean")]
		public bool IsAManualAccount { get; set; }



		/// <summary>
		/// AnalysisCodingLevel property
		/// </summary>
		[XmlAttribute("AnalysisCodingLevel", DataType = "int")]
		public Int32 AnalysisCodingLevel { get; set; }



		/// <summary>
		/// ECodingAccountUID property
		/// </summary>
		[XmlAttribute("ECodingAccountUID", DataType = "int")]
		public Int32 ECodingAccountUID { get; set; }



		/// <summary>
		/// CodingSortOrder property
		/// </summary>
		[XmlAttribute("CodingSortOrder", DataType = "int")]
		public Int32 CodingSortOrder { get; set; }



		/// <summary>
		/// ManualAccountType property
		/// </summary>
		[XmlAttribute("ManualAccountType", DataType = "int")]
		public Int32 ManualAccountType { get; set; }



		/// <summary>
		/// ManualAccountInstitution property
		/// </summary>
		[XmlAttribute("ManualAccountInstitution", DataType = "string")]
		public String ManualAccountInstitution { get; set; }



		/// <summary>
		/// ManualAccountSentToAdmin property
		/// </summary>
		[XmlAttribute("ManualAccountSentToAdmin", DataType = "boolean")]
		public bool ManualAccountSentToAdmin { get; set; }



		/// <summary>
		/// SpareString property
		/// </summary>
		[XmlAttribute("SpareString", DataType = "string")]
		public String SpareString { get; set; }



		/// <summary>
		/// IsAProvisionalAccount property
		/// </summary>
		[XmlAttribute("IsAProvisionalAccount", DataType = "boolean")]
		public bool IsAProvisionalAccount { get; set; }



		/// <summary>
		/// SpareNumber property
		/// </summary>
		[XmlAttribute("SpareNumber", DataType = "int")]
		public Int32 SpareNumber { get; set; }



		/// <summary>
		/// SpareByte property
		/// </summary>
		[XmlAttribute("SpareByte", DataType = "unsignedByte")]
		public byte SpareByte { get; set; }



		/// <summary>
		/// HDEColumnOrder property
		/// </summary>
		[XmlArray("HDEColumnOrders"),XmlArrayItem("HDEColumnOrder", DataType = "unsignedByte")]
		public byte[] HDEColumnOrder { get; set; }


		/// <summary>
		/// HDEColumnWidth property
		/// </summary>
		[XmlArray("HDEColumnWidths"),XmlArrayItem("HDEColumnWidth", DataType = "int")]
		public Int32[] HDEColumnWidth { get; set; }


		/// <summary>
		/// HDEColumnisHidden property
		/// </summary>
		[XmlArray("HDEColumnisHiddens"),XmlArrayItem("HDEColumnisHidden", DataType = "boolean")]
		public bool[] HDEColumnisHidden { get; set; }


		/// <summary>
		/// HDEColumnisNotEditable property
		/// </summary>
		[XmlArray("HDEColumnisNotEditables"),XmlArrayItem("HDEColumnisNotEditable", DataType = "boolean")]
		public bool[] HDEColumnisNotEditable { get; set; }


		/// <summary>
		/// HDESortOrder property
		/// </summary>
		[XmlAttribute("HDESortOrder", DataType = "int")]
		public Int32 HDESortOrder { get; set; }



		/// <summary>
		/// MDEColumnOrder property
		/// </summary>
		[XmlArray("MDEColumnOrders"),XmlArrayItem("MDEColumnOrder", DataType = "unsignedByte")]
		public byte[] MDEColumnOrder { get; set; }


		/// <summary>
		/// MDEColumnWidth property
		/// </summary>
		[XmlArray("MDEColumnWidths"),XmlArrayItem("MDEColumnWidth", DataType = "int")]
		public Int32[] MDEColumnWidth { get; set; }


		/// <summary>
		/// MDEColumnisHidden property
		/// </summary>
		[XmlArray("MDEColumnisHiddens"),XmlArrayItem("MDEColumnisHidden", DataType = "boolean")]
		public bool[] MDEColumnisHidden { get; set; }


		/// <summary>
		/// MDEColumnisNotEditable property
		/// </summary>
		[XmlArray("MDEColumnisNotEditables"),XmlArrayItem("MDEColumnisNotEditable", DataType = "boolean")]
		public bool[] MDEColumnisNotEditable { get; set; }


		/// <summary>
		/// MDESortOrder property
		/// </summary>
		[XmlAttribute("MDESortOrder", DataType = "int")]
		public Int32 MDESortOrder { get; set; }



		/// <summary>
		/// DISColumnOrder property
		/// </summary>
		[XmlArray("DISColumnOrders"),XmlArrayItem("DISColumnOrder", DataType = "unsignedByte")]
		public byte[] DISColumnOrder { get; set; }


		/// <summary>
		/// DISColumnWidth property
		/// </summary>
		[XmlArray("DISColumnWidths"),XmlArrayItem("DISColumnWidth", DataType = "int")]
		public Int32[] DISColumnWidth { get; set; }


		/// <summary>
		/// DISColumnisHidden property
		/// </summary>
		[XmlArray("DISColumnisHiddens"),XmlArrayItem("DISColumnisHidden", DataType = "boolean")]
		public bool[] DISColumnisHidden { get; set; }


		/// <summary>
		/// DISColumnisNotEditable property
		/// </summary>
		[XmlArray("DISColumnisNotEditables"),XmlArrayItem("DISColumnisNotEditable", DataType = "boolean")]
		public bool[] DISColumnisNotEditable { get; set; }


		/// <summary>
		/// DISSortOrder property
		/// </summary>
		[XmlAttribute("DISSortOrder", DataType = "int")]
		public Int32 DISSortOrder { get; set; }



		/// <summary>
		/// DesktopSuperLedgerID property
		/// </summary>
		[XmlAttribute("DesktopSuperLedgerID", DataType = "int")]
		public Int32 DesktopSuperLedgerID { get; set; }



		/// <summary>
		/// CurrencyCode property
		/// </summary>
		[XmlAttribute("CurrencyCode", DataType = "string")]
		public String CurrencyCode { get; set; }



		/// <summary>
		/// DefaultForexSource property
		/// </summary>
		[XmlAttribute("DefaultForexSource", DataType = "string")]
		public String DefaultForexSource { get; set; }



		/// <summary>
		/// DefaultForexDescription property
		/// </summary>
		[XmlAttribute("DefaultForexDescription", DataType = "string")]
		public String DefaultForexDescription { get; set; }



		/// <summary>
		/// SuperFundLedgerCode property
		/// </summary>
		[XmlAttribute("SuperFundLedgerCode", DataType = "string")]
		public String SuperFundLedgerCode { get; set; }



	}


}


