// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - BudgetDetail class
	/// </summary>
	public partial class BKBudgetDetail
	{


		/// <summary>
		/// AccountCode property
		/// </summary>
		[XmlAttribute("AccountCode", DataType = "string")]
		public String AccountCode { get; set; }



		/// <summary>
		/// Budget property
		/// </summary>
		[XmlArray("Budgets"),XmlArrayItem("Budget", DataType = "long")]
		public Int64[] Budget { get; set; }


		/// <summary>
		/// QtyBudget property
		/// </summary>
		[XmlArray("QtyBudgets"),XmlArrayItem("QtyBudget", DataType = "long")]
		public Int64[] QtyBudget { get; set; }


		/// <summary>
		/// EachBudget property
		/// </summary>
		[XmlArray("EachBudgets"),XmlArrayItem("EachBudget", DataType = "long")]
		public Int64[] EachBudget { get; set; }


	}


}


