// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - DiskLog class
	/// </summary>
	public partial class BKDiskLog
	{


		/// <summary>
		/// DiskID property
		/// </summary>
		[XmlAttribute("DiskID", DataType = "string")]
		public String DiskID { get; set; }



		/// <summary>
		/// DateDownloaded property
		/// </summary>
		[XmlAttribute("DateDownloaded", DataType = "int")]
		public Int32 DateDownloaded { get; set; }



		/// <summary>
		/// NoofAccounts property
		/// </summary>
		[XmlAttribute("NoofAccounts", DataType = "int")]
		public Int32 NoofAccounts { get; set; }



		/// <summary>
		/// NoofEntries property
		/// </summary>
		[XmlAttribute("NoofEntries", DataType = "int")]
		public Int32 NoofEntries { get; set; }



	}


}


