// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - JobHeading class
	/// </summary>
	public partial class BKJobHeading
	{


		/// <summary>
		/// Heading property
		/// </summary>
		[XmlAttribute("Heading", DataType = "string")]
		public String Heading { get; set; }



		/// <summary>
		/// LRN property
		/// </summary>
		[XmlAttribute("LRN", DataType = "int")]
		public Int32 LRN { get; set; }



		/// <summary>
		/// DateCompleted property
		/// </summary>
		[XmlAttribute("DateCompleted", DataType = "int")]
		public Int32 DateCompleted { get; set; }



		/// <summary>
		/// Code property
		/// </summary>
		[XmlAttribute("Code", DataType = "string")]
		public String Code { get; set; }



	}


}


