// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - Macro class
	/// </summary>
	public partial class BKMacro
	{


		/// <summary>
		/// Code property
		/// </summary>
		[XmlAttribute("Code", DataType = "string")]
		public String Code { get; set; }



		/// <summary>
		/// Description property
		/// </summary>
		[XmlAttribute("Description", DataType = "string")]
		public String Description { get; set; }



	}


}


