// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using BankLink.Practice.Common.Entities;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - Macro class
	/// </summary>
	public partial class BKMacro 
	{


		/// <summary>
		/// Code property
		/// </summary>
		[XmlAttribute("Code", DataType = "string")]
		public String Code { get; set; }



		/// <summary>
		/// Description property
		/// </summary>
		[XmlAttribute("Description", DataType = "string")]
		public String Description { get; set; }


		/// <summary>
		/// Class Begin Token
		/// </summary>
		public const byte BeginToken = 240;
		/// <summary>
		/// Class End Token
		/// </summary>
		public const byte EndToken = 241;
		/// <summary>
		/// Write to BKStream
		/// </summary>
		public void WriteBKStream(BankLinkTokenStreamWriter s)
		{
			s.WriteToken(240);
			s.WriteShortStringValue(242, Code);
			s.WriteShortStringValue(243, Description);
			s.WriteToken(241);
		}

		/// <summary>
		/// Default Constructor 
		/// </summary>
		public BKMacro ()
		{}
		/// <summary>
		/// Construct from BKStreamReader
		/// </summary>
		public BKMacro (BankLinkTokenStreamReader s)
		{
			var token = BeginToken;
			while (token != EndToken)
			{
				switch (token)
				{
			case 242 :
				Code = s.ReadShortStringValue("Code");
				break;
			case 243 :
				Description = s.ReadShortStringValue("Description");
				break;
			case BeginToken :
			case EndToken :
				break;
			default:
				throw new Exception(string.Format("unexpected Code: {0} reading Macro",token) );
				}
			token = s.ReadToken();
			}
		}


	}


}


