// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - MemorisationDetail class
	/// </summary>
	public partial class BKMemorisationDetail
	{


		/// <summary>
		/// SequenceNo property
		/// </summary>
		[XmlAttribute("SequenceNo", DataType = "int")]
		public Int32 SequenceNo { get; set; }



		/// <summary>
		/// Type property
		/// </summary>
		[XmlAttribute("Type", DataType = "unsignedByte")]
		public byte Type { get; set; }



		/// <summary>
		/// Amount property
		/// </summary>
		[XmlAttribute("Amount", DataType = "long")]
		public Int64 Amount { get; set; }



		/// <summary>
		/// Reference property
		/// </summary>
		[XmlAttribute("Reference", DataType = "string")]
		public String Reference { get; set; }



		/// <summary>
		/// Particulars property
		/// </summary>
		[XmlAttribute("Particulars", DataType = "string")]
		public String Particulars { get; set; }



		/// <summary>
		/// Analysis property
		/// </summary>
		[XmlAttribute("Analysis", DataType = "string")]
		public String Analysis { get; set; }



		/// <summary>
		/// OtherParty property
		/// </summary>
		[XmlAttribute("OtherParty", DataType = "string")]
		public String OtherParty { get; set; }



		/// <summary>
		/// StatementDetails property
		/// </summary>
		[XmlAttribute("StatementDetails", DataType = "string")]
		public String StatementDetails { get; set; }



		/// <summary>
		/// MatchonAmount property
		/// </summary>
		[XmlAttribute("MatchonAmount", DataType = "unsignedByte")]
		public byte MatchonAmount { get; set; }



		/// <summary>
		/// MatchonAnalysis property
		/// </summary>
		[XmlAttribute("MatchonAnalysis", DataType = "boolean")]
		public bool MatchonAnalysis { get; set; }



		/// <summary>
		/// MatchonOtherParty property
		/// </summary>
		[XmlAttribute("MatchonOtherParty", DataType = "boolean")]
		public bool MatchonOtherParty { get; set; }



		/// <summary>
		/// MatchonNotes property
		/// </summary>
		[XmlAttribute("MatchonNotes", DataType = "boolean")]
		public bool MatchonNotes { get; set; }



		/// <summary>
		/// MatchonParticulars property
		/// </summary>
		[XmlAttribute("MatchonParticulars", DataType = "boolean")]
		public bool MatchonParticulars { get; set; }



		/// <summary>
		/// MatchonRefce property
		/// </summary>
		[XmlAttribute("MatchonRefce", DataType = "boolean")]
		public bool MatchonRefce { get; set; }



		/// <summary>
		/// MatchOnStatementDetails property
		/// </summary>
		[XmlAttribute("MatchOnStatementDetails", DataType = "boolean")]
		public bool MatchOnStatementDetails { get; set; }



		/// <summary>
		/// PayeeNumber property
		/// </summary>
		[XmlAttribute("PayeeNumber", DataType = "int")]
		public Int32 PayeeNumber { get; set; }



		/// <summary>
		/// FromMasterList property
		/// </summary>
		[XmlAttribute("FromMasterList", DataType = "boolean")]
		public bool FromMasterList { get; set; }



		/// <summary>
		/// Notes property
		/// </summary>
		[XmlAttribute("Notes", DataType = "string")]
		public String Notes { get; set; }



		/// <summary>
		/// DateLastApplied property
		/// </summary>
		[XmlAttribute("DateLastApplied", DataType = "int")]
		public Int32 DateLastApplied { get; set; }



		/// <summary>
		/// UseAccountingSystem property
		/// </summary>
		[XmlAttribute("UseAccountingSystem", DataType = "boolean")]
		public bool UseAccountingSystem { get; set; }



		/// <summary>
		/// AccountingSystem property
		/// </summary>
		[XmlAttribute("AccountingSystem", DataType = "unsignedByte")]
		public byte AccountingSystem { get; set; }



		/// <summary>
		/// FromDate property
		/// </summary>
		[XmlAttribute("FromDate", DataType = "int")]
		public Int32 FromDate { get; set; }



		/// <summary>
		/// UntilDate property
		/// </summary>
		[XmlAttribute("UntilDate", DataType = "int")]
		public Int32 UntilDate { get; set; }



	}


}


