// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - MoreClient class
	/// </summary>
	public partial class BKMoreClient
	{


		/// <summary>
		/// BASDontPrintFuelSheet property
		/// </summary>
		[XmlAttribute("BASDontPrintFuelSheet", DataType = "boolean")]
		public bool BASDontPrintFuelSheet { get; set; }



		/// <summary>
		/// Archived property
		/// </summary>
		[XmlAttribute("Archived", DataType = "boolean")]
		public bool Archived { get; set; }



		/// <summary>
		/// JournalProcessingDuration property
		/// </summary>
		[XmlAttribute("JournalProcessingDuration", DataType = "unsignedByte")]
		public byte JournalProcessingDuration { get; set; }



	}


}


