// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - Payee class
	/// </summary>
	public partial class BKPayee
	{


		/// <summary>
		/// Number property
		/// </summary>
		[XmlAttribute("Number", DataType = "int")]
		public Int32 Number { get; set; }



		/// <summary>
		/// Name property
		/// </summary>
		[XmlAttribute("Name", DataType = "string")]
		public String Name { get; set; }



		/// <summary>
		/// Account property
		/// </summary>
		[XmlArray("Accounts"),XmlArrayItem("Account", DataType = "string")]
		public String[] Account { get; set; }


		/// <summary>
		/// Percentage property
		/// </summary>
		[XmlArray("Percentages"),XmlArrayItem("Percentage", DataType = "long")]
		public Int64[] Percentage { get; set; }


		/// <summary>
		/// GSTClass property
		/// </summary>
		[XmlArray("GSTClass"),XmlArrayItem("GSTClas", DataType = "unsignedByte")]
		public byte[] GSTClass { get; set; }


		/// <summary>
		/// GSTHasBeenEdited property
		/// </summary>
		[XmlArray("GSTHasBeenEditeds"),XmlArrayItem("GSTHasBeenEdited", DataType = "boolean")]
		public bool[] GSTHasBeenEdited { get; set; }


		/// <summary>
		/// GLNarration property
		/// </summary>
		[XmlArray("GLNarrations"),XmlArrayItem("GLNarration", DataType = "string")]
		public String[] GLNarration { get; set; }


	}


}


