// **********************************************************
// This file is Auto generated by DBGen
// Any changes will be lost when the file is regenerated
// **********************************************************
using System;
using System.Xml.Serialization;


namespace BankLink.Practice.BooksIO
{
	/// <summary>
	/// BK - Transaction class
	/// </summary>
	public partial class BKTransaction
	{


		/// <summary>
		/// SequenceNo property
		/// </summary>
		[XmlAttribute("SequenceNo", DataType = "int")]
		public Int32 SequenceNo { get; set; }



		/// <summary>
		/// LRNNOWUNUSED property
		/// </summary>
		[XmlAttribute("LRNNOWUNUSED", DataType = "int")]
		public Int32 LRNNOWUNUSED { get; set; }



		/// <summary>
		/// Type property
		/// </summary>
		[XmlAttribute("Type", DataType = "unsignedByte")]
		public byte Type { get; set; }



		/// <summary>
		/// Source property
		/// </summary>
		[XmlAttribute("Source", DataType = "unsignedByte")]
		public byte Source { get; set; }



		/// <summary>
		/// DatePresented property
		/// </summary>
		[XmlAttribute("DatePresented", DataType = "int")]
		public Int32 DatePresented { get; set; }



		/// <summary>
		/// DateEffective property
		/// </summary>
		[XmlAttribute("DateEffective", DataType = "int")]
		public Int32 DateEffective { get; set; }



		/// <summary>
		/// DateTransferred property
		/// </summary>
		[XmlAttribute("DateTransferred", DataType = "int")]
		public Int32 DateTransferred { get; set; }



		/// <summary>
		/// Amount property
		/// </summary>
		[XmlAttribute("Amount", DataType = "long")]
		public Int64 Amount { get; set; }



		/// <summary>
		/// GSTClass property
		/// </summary>
		[XmlAttribute("GSTClass", DataType = "unsignedByte")]
		public byte GSTClass { get; set; }



		/// <summary>
		/// GSTAmount property
		/// </summary>
		[XmlAttribute("GSTAmount", DataType = "long")]
		public Int64 GSTAmount { get; set; }



		/// <summary>
		/// HasBeenEdited property
		/// </summary>
		[XmlAttribute("HasBeenEdited", DataType = "boolean")]
		public bool HasBeenEdited { get; set; }



		/// <summary>
		/// Quantity property
		/// </summary>
		[XmlAttribute("Quantity", DataType = "long")]
		public Int64 Quantity { get; set; }



		/// <summary>
		/// ChequeNumber property
		/// </summary>
		[XmlAttribute("ChequeNumber", DataType = "int")]
		public Int32 ChequeNumber { get; set; }



		/// <summary>
		/// Reference property
		/// </summary>
		[XmlAttribute("Reference", DataType = "string")]
		public String Reference { get; set; }



		/// <summary>
		/// Particulars property
		/// </summary>
		[XmlAttribute("Particulars", DataType = "string")]
		public String Particulars { get; set; }



		/// <summary>
		/// Analysis property
		/// </summary>
		[XmlAttribute("Analysis", DataType = "string")]
		public String Analysis { get; set; }



		/// <summary>
		/// OrigBB property
		/// </summary>
		[XmlAttribute("OrigBB", DataType = "string")]
		public String OrigBB { get; set; }



		/// <summary>
		/// OtherParty property
		/// </summary>
		[XmlAttribute("OtherParty", DataType = "string")]
		public String OtherParty { get; set; }



		/// <summary>
		/// OldNarration property
		/// </summary>
		[XmlAttribute("OldNarration", DataType = "string")]
		public String OldNarration { get; set; }



		/// <summary>
		/// Account property
		/// </summary>
		[XmlAttribute("Account", DataType = "string")]
		public String Account { get; set; }



		/// <summary>
		/// CodedBy property
		/// </summary>
		[XmlAttribute("CodedBy", DataType = "unsignedByte")]
		public byte CodedBy { get; set; }



		/// <summary>
		/// PayeeNumber property
		/// </summary>
		[XmlAttribute("PayeeNumber", DataType = "int")]
		public Int32 PayeeNumber { get; set; }



		/// <summary>
		/// Locked property
		/// </summary>
		[XmlAttribute("Locked", DataType = "boolean")]
		public bool Locked { get; set; }



		/// <summary>
		/// BankLinkID property
		/// </summary>
		[XmlAttribute("BankLinkID", DataType = "int")]
		public Int32 BankLinkID { get; set; }



		/// <summary>
		/// GSTHasBeenEdited property
		/// </summary>
		[XmlAttribute("GSTHasBeenEdited", DataType = "boolean")]
		public bool GSTHasBeenEdited { get; set; }



		/// <summary>
		/// MatchedItemID property
		/// </summary>
		[XmlAttribute("MatchedItemID", DataType = "int")]
		public Int32 MatchedItemID { get; set; }



		/// <summary>
		/// UPIState property
		/// </summary>
		[XmlAttribute("UPIState", DataType = "unsignedByte")]
		public byte UPIState { get; set; }



		/// <summary>
		/// OriginalReference property
		/// </summary>
		[XmlAttribute("OriginalReference", DataType = "string")]
		public String OriginalReference { get; set; }



		/// <summary>
		/// OriginalSource property
		/// </summary>
		[XmlAttribute("OriginalSource", DataType = "unsignedByte")]
		public byte OriginalSource { get; set; }



		/// <summary>
		/// OriginalType property
		/// </summary>
		[XmlAttribute("OriginalType", DataType = "unsignedByte")]
		public byte OriginalType { get; set; }



		/// <summary>
		/// OriginalChequeNumber property
		/// </summary>
		[XmlAttribute("OriginalChequeNumber", DataType = "int")]
		public Int32 OriginalChequeNumber { get; set; }



		/// <summary>
		/// OriginalAmount property
		/// </summary>
		[XmlAttribute("OriginalAmount", DataType = "long")]
		public Int64 OriginalAmount { get; set; }



		/// <summary>
		/// Notes property
		/// </summary>
		[XmlAttribute("Notes", DataType = "string")]
		public String Notes { get; set; }



		/// <summary>
		/// ECodingImportNotes property
		/// </summary>
		[XmlAttribute("ECodingImportNotes", DataType = "string")]
		public String ECodingImportNotes { get; set; }



		/// <summary>
		/// ECodingTransactionUID property
		/// </summary>
		[XmlAttribute("ECodingTransactionUID", DataType = "int")]
		public Int32 ECodingTransactionUID { get; set; }



		/// <summary>
		/// GLNarration property
		/// </summary>
		[XmlAttribute("GLNarration", DataType = "string")]
		public String GLNarration { get; set; }



		/// <summary>
		/// StatementDetails property
		/// </summary>
		[XmlAttribute("StatementDetails", DataType = "string")]
		public String StatementDetails { get; set; }



		/// <summary>
		/// TaxInvoiceAvailable property
		/// </summary>
		[XmlAttribute("TaxInvoiceAvailable", DataType = "boolean")]
		public bool TaxInvoiceAvailable { get; set; }



		/// <summary>
		/// SFImputedCredit property
		/// </summary>
		[XmlAttribute("SFImputedCredit", DataType = "long")]
		public Int64 SFImputedCredit { get; set; }



		/// <summary>
		/// SFTaxFreeDist property
		/// </summary>
		[XmlAttribute("SFTaxFreeDist", DataType = "long")]
		public Int64 SFTaxFreeDist { get; set; }



		/// <summary>
		/// SFTaxExemptDist property
		/// </summary>
		[XmlAttribute("SFTaxExemptDist", DataType = "long")]
		public Int64 SFTaxExemptDist { get; set; }



		/// <summary>
		/// SFTaxDeferredDist property
		/// </summary>
		[XmlAttribute("SFTaxDeferredDist", DataType = "long")]
		public Int64 SFTaxDeferredDist { get; set; }



		/// <summary>
		/// SFTFNCredits property
		/// </summary>
		[XmlAttribute("SFTFNCredits", DataType = "long")]
		public Int64 SFTFNCredits { get; set; }



		/// <summary>
		/// SFForeignIncome property
		/// </summary>
		[XmlAttribute("SFForeignIncome", DataType = "long")]
		public Int64 SFForeignIncome { get; set; }



		/// <summary>
		/// SFForeignTaxCredits property
		/// </summary>
		[XmlAttribute("SFForeignTaxCredits", DataType = "long")]
		public Int64 SFForeignTaxCredits { get; set; }



		/// <summary>
		/// SFCapitalGainsIndexed property
		/// </summary>
		[XmlAttribute("SFCapitalGainsIndexed", DataType = "long")]
		public Int64 SFCapitalGainsIndexed { get; set; }



		/// <summary>
		/// SFCapitalGainsDisc property
		/// </summary>
		[XmlAttribute("SFCapitalGainsDisc", DataType = "long")]
		public Int64 SFCapitalGainsDisc { get; set; }



		/// <summary>
		/// SFSuperFieldsEdited property
		/// </summary>
		[XmlAttribute("SFSuperFieldsEdited", DataType = "boolean")]
		public bool SFSuperFieldsEdited { get; set; }



		/// <summary>
		/// SFCapitalGainsOther property
		/// </summary>
		[XmlAttribute("SFCapitalGainsOther", DataType = "long")]
		public Int64 SFCapitalGainsOther { get; set; }



		/// <summary>
		/// SFOtherExpenses property
		/// </summary>
		[XmlAttribute("SFOtherExpenses", DataType = "long")]
		public Int64 SFOtherExpenses { get; set; }



		/// <summary>
		/// SFCGTDate property
		/// </summary>
		[XmlAttribute("SFCGTDate", DataType = "int")]
		public Int32 SFCGTDate { get; set; }



		/// <summary>
		/// ExternalGUID property
		/// </summary>
		[XmlAttribute("ExternalGUID", DataType = "string")]
		public String ExternalGUID { get; set; }



		/// <summary>
		/// DocumentTitle property
		/// </summary>
		[XmlAttribute("DocumentTitle", DataType = "string")]
		public String DocumentTitle { get; set; }



		/// <summary>
		/// DocumentStatusUpdateRequired property
		/// </summary>
		[XmlAttribute("DocumentStatusUpdateRequired", DataType = "boolean")]
		public bool DocumentStatusUpdateRequired { get; set; }



		/// <summary>
		/// BankLinkUID property
		/// </summary>
		[XmlAttribute("BankLinkUID", DataType = "string")]
		public String BankLinkUID { get; set; }



		/// <summary>
		/// NotesRead property
		/// </summary>
		[XmlAttribute("NotesRead", DataType = "boolean")]
		public bool NotesRead { get; set; }



		/// <summary>
		/// ImportNotesRead property
		/// </summary>
		[XmlAttribute("ImportNotesRead", DataType = "boolean")]
		public bool ImportNotesRead { get; set; }



		/// <summary>
		/// SpareString property
		/// </summary>
		[XmlAttribute("SpareString", DataType = "string")]
		public String SpareString { get; set; }



		/// <summary>
		/// SpareBoolean property
		/// </summary>
		[XmlAttribute("SpareBoolean", DataType = "boolean")]
		public bool SpareBoolean { get; set; }



		/// <summary>
		/// SFFranked property
		/// </summary>
		[XmlAttribute("SFFranked", DataType = "long")]
		public Int64 SFFranked { get; set; }



		/// <summary>
		/// SFUnfranked property
		/// </summary>
		[XmlAttribute("SFUnfranked", DataType = "long")]
		public Int64 SFUnfranked { get; set; }



		/// <summary>
		/// SFInterest property
		/// </summary>
		[XmlAttribute("SFInterest", DataType = "long")]
		public Int64 SFInterest { get; set; }



		/// <summary>
		/// SFCapitalGainsForeignDisc property
		/// </summary>
		[XmlAttribute("SFCapitalGainsForeignDisc", DataType = "long")]
		public Int64 SFCapitalGainsForeignDisc { get; set; }



		/// <summary>
		/// SFRent property
		/// </summary>
		[XmlAttribute("SFRent", DataType = "long")]
		public Int64 SFRent { get; set; }



		/// <summary>
		/// SFSpecialIncome property
		/// </summary>
		[XmlAttribute("SFSpecialIncome", DataType = "long")]
		public Int64 SFSpecialIncome { get; set; }



		/// <summary>
		/// SFOtherTaxCredit property
		/// </summary>
		[XmlAttribute("SFOtherTaxCredit", DataType = "long")]
		public Int64 SFOtherTaxCredit { get; set; }



		/// <summary>
		/// SFNonResidentTax property
		/// </summary>
		[XmlAttribute("SFNonResidentTax", DataType = "long")]
		public Int64 SFNonResidentTax { get; set; }



		/// <summary>
		/// SFMemberID property
		/// </summary>
		[XmlAttribute("SFMemberID", DataType = "string")]
		public String SFMemberID { get; set; }



		/// <summary>
		/// SFForeignCapitalGainsCredit property
		/// </summary>
		[XmlAttribute("SFForeignCapitalGainsCredit", DataType = "long")]
		public Int64 SFForeignCapitalGainsCredit { get; set; }



		/// <summary>
		/// SFMemberComponent property
		/// </summary>
		[XmlAttribute("SFMemberComponent", DataType = "unsignedByte")]
		public byte SFMemberComponent { get; set; }



		/// <summary>
		/// SFFundID property
		/// </summary>
		[XmlAttribute("SFFundID", DataType = "int")]
		public Int32 SFFundID { get; set; }



		/// <summary>
		/// SFMemberAccountID property
		/// </summary>
		[XmlAttribute("SFMemberAccountID", DataType = "int")]
		public Int32 SFMemberAccountID { get; set; }



		/// <summary>
		/// SFFundCode property
		/// </summary>
		[XmlAttribute("SFFundCode", DataType = "string")]
		public String SFFundCode { get; set; }



		/// <summary>
		/// SFMemberAccountCode property
		/// </summary>
		[XmlAttribute("SFMemberAccountCode", DataType = "string")]
		public String SFMemberAccountCode { get; set; }



		/// <summary>
		/// SFTransactionID property
		/// </summary>
		[XmlAttribute("SFTransactionID", DataType = "int")]
		public Int32 SFTransactionID { get; set; }



		/// <summary>
		/// SFTransactionCode property
		/// </summary>
		[XmlAttribute("SFTransactionCode", DataType = "string")]
		public String SFTransactionCode { get; set; }



		/// <summary>
		/// SFCapitalGainsFractionHalf property
		/// </summary>
		[XmlAttribute("SFCapitalGainsFractionHalf", DataType = "boolean")]
		public bool SFCapitalGainsFractionHalf { get; set; }



		/// <summary>
		/// JobCode property
		/// </summary>
		[XmlAttribute("JobCode", DataType = "string")]
		public String JobCode { get; set; }



		/// <summary>
		/// SpareMoney1 property
		/// </summary>
		[XmlAttribute("SpareMoney1", DataType = "long")]
		public Int64 SpareMoney1 { get; set; }



		/// <summary>
		/// SpareMoney2 property
		/// </summary>
		[XmlAttribute("SpareMoney2", DataType = "long")]
		public Int64 SpareMoney2 { get; set; }



		/// <summary>
		/// CoreTransactionID property
		/// </summary>
		[XmlAttribute("CoreTransactionID", DataType = "int")]
		public Int32 CoreTransactionID { get; set; }



		/// <summary>
		/// TransferedToOnline property
		/// </summary>
		[XmlAttribute("TransferedToOnline", DataType = "boolean")]
		public bool TransferedToOnline { get; set; }



		/// <summary>
		/// CoreTransactionIDHigh property
		/// </summary>
		[XmlAttribute("CoreTransactionIDHigh", DataType = "int")]
		public Int32 CoreTransactionIDHigh { get; set; }



	}


}


