contains
  // The following is the list of units to be contained in the
  // Raize Components data-aware runtime packages.

  RzDBBnEd         in 'RzDBBnEd.pas',
  RzDBChk          in 'RzDBChk.pas',
  RzDBCmbo         in 'RzDBCmbo.pas',
  RzDBDTP          in 'RzDBDTP.pas',
  RzDBEdit         in 'RzDBEdit.pas',
  RzDBGrid         in 'RzDBGrid.pas',
  RzDBLbl          in 'RzDBLbl.pas',
  RzDBList         in 'RzDBList.pas',
  RzDBLook         in 'RzDBLook.pas',
  RzDBLookupForm   in 'RzDBLookupForm.pas',
  RzDBNav          in 'RzDBNav.pas',
  RzDBProg         in 'RzDBProg.pas',
  RzDBRGrp         in 'RzDBRGrp.pas',
  RzDBSpin         in 'RzDBSpin.pas',
  RzDBStat         in 'RzDBStat.pas',
  RzDBTrak         in 'RzDBTrak.pas';
