  ErrFileIsNotXLS='文件 "%s"无效';
  ErrCantReadFile='无法读取"%s"文件';
  ErrExcelInvalid= '读取记录失败. 文件无效';
  ErrCantWriteOutput='无法创建文件 "%s"';
  ErrCantWrite='保存文件出错';

  ErrFileNotFound='没有发现文件"%s"';
  ErrStreamNotFound='无法打开"%s"流';

  ErrExtRefsNotSupported='不支持外部引用';

  ErrWrongExcelRecord='0x%x 记录无效';

  ErrBadToken='读取公式出错, 不支持Token Id: 0x%2x ';
  ErrBadFormula='不支持位于行 %d, 列 %d 的公式. Token Id: 0x%2x';
  ErrBadName='工作表名错误: "%s". Token Id: 0x%2x';
  ErrBadCF='无效的条件格式. Token Id: 0x%2x';
  ErrBadChartFormula='图表公式错误. Token Id: 0x%2x';

  Err3DRef='不支持外部公式引用';

  ErrReadingRecord='读取记录出错';

  ErrInvalidVersion='模板文件版本无效';

  ErrTooManyEntries= '过多的条目 (%d 超过最大支持数%d)';
  ErrRecordNotSupported='模板包括不支持的记录: %4x';

  ErrSectionNotLoaded='工作簿的一部分无法读取';

  ErrInvalidContinue='试图在一个记录上添加多个CONTINUE记录';
  ErrStringTooLarge='字符串太长';
  ErrInvalidDrawing='文件中含有不支持的绘图记录';
  ErrInvalidCF='无效条件格式公式';

  ErrDuplicatedSheetName='工作表名已存在: %s';

  ErrDupRow='重复的ROW记录' ;
  ErrRowMissing=' %d行的ROW记录丢失';

  ErrBadCopyRows='使用无效参数调用InsertAndCopyRows';
  ErrInvalidSheetNo='工作表序号 "%d" 无效. 必须介于 %d -- %d之间';

  ErrBadRowCount='ROW记录数与单元格数不相同';

  ErrEscherNotLoaded='Escher记录没有完全加载';
  ErrLoadingEscher='加载Escher记录出错';
  ErrBStroreDuplicated='加载Escher记录出错. 重复的BStore';
  ErrDgDuplicated='加载Escher记录出错. 重复的Dg';
  ErrDggDuplicated='加载Escher记录出错. 重复的Dgg';
  ErrsolverDuplicated='加载Escher记录出错. 重复的Solver容器';

  ErrChangingEscher='无法处理Escher记录';

  ErrInternal='逻辑错误';

  ErrCantCopyPictFmla='不能复制内嵌的对象';

  ErrInvalidErrStr='无效的单元格错误代码: "%s"';
  ErrInvalidCellValue='无效的单元格值: "%s"';

  ErrCantWriteToFile='无法写文件 "%s".检查文件是否被另外的用户打开';

  ErrShrFmlaNotFound='无法找到共享的公式';

  //Strings
  ErrInvalidStrLenLength='StrLenLength应为1或 2';
  ErrInvalidStringRecord='无效字符记录';

  ErrNotImplemented='文件没有实现该类型的记录: %s';

  BaseSheetName='工作表';

  ErrNoDataSet='没有设置数据集';
  ErrReportNotFound='报表不存在: %s';
  ErrTooManyPageBreaks='分页符过多';

  ErrInvalidRow='无效行 (%d)';
  ErrInvalidCol='无效列 (%d)';

  ErrXlsIndexOutBounds='属性 "%d"的索引 "%s" 没有介于 %d-%d之间';

  ErrFileIsPasswordProtected='文件有密码保护';

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';