  ErrFileIsNotXLS='Tiedosto "%s" on epäkelpo';
  ErrCantReadFile='Tiedosto "%s" ei ole luettavissa';
  ErrExcelInvalid= 'Virhe luettaessa Excelin tietoja. Tiedosto on epäkelpo';
  ErrCantWriteOutput='"%s"-tulostiedoston luominen epäonnistui';
  ErrCantWrite='Virhe kirjoitettaessa tuolostiedostoa';

  ErrFileNotFound='Tiedostoa "%s" ei löydy';
  ErrStreamNotFound='"%s"-virran avaaminen ei onnistunut';

  ErrExtRefsNotSupported='FlexCel ei tue ulkoisia viittauksia toiseen työkirjaan';

  ErrWrongExcelRecord='Tietue, jonka tunniste on 0x%x, on epäkelpo';

  ErrBadToken='Kaavan luku epäonnistui, tokenia, jonka tunniste on 0x%2x ei tueta';
  ErrBadFormula='Kaavaa rivillä %d, sarakkeessa %d ei ole tuettu. Tokenin tunniste: 0x%2x';
  ErrBadName='Virheellinen työkirjan nimi: "%s". Tokenin tunniste: 0x%2x';
  ErrBadCF='Virheellinen ehdollinen muotoilu. Tokenin tunniste: 0x%2x';
  ErrBadChartFormula='Virhe kaavion kaavassa. Tokenin tunniste: 0x%2x';

  Err3DRef='Kaavassa, joka ei tue viittaamista toiseen työkirjaan on viittaus toiseen työkirjaan.';

  ErrReadingRecord='Virhe luettaessa tietuetta';

  ErrInvalidVersion='Mallitiedosto on tallennettu epäkelvolla Excelin versiolla';

  ErrTooManyEntries= 'Liian monta syötettä tämäntyyppiselle tietueelle (%d kpl, maksimi %d)';
  ErrRecordNotSupported='Malli sisältää tietueen, jota ei tueta: %4x';

  ErrSectionNotLoaded='Työkirjan osa lataamatta';

  ErrInvalidContinue='Tietueeseen yritettiin lisätä useampi kuin yksi CONTINUE-tietue';
  ErrStringTooLarge='Merkkijono on liian pitkä';
  ErrInvalidDrawing='Tiedostossa on graafinen tietue, jota ei tueta';
  ErrInvalidCF='Epäkelpo ehdollisen muotoilun tietue';

  ErrDuplicatedSheetName='Taulukko %s on jo olemassa';

  ErrDupRow='Toinen samanlainen ROW-tietue on jo olemassa' ;
  ErrRowMissing='ROW-tietue puuttuu riviltä %d';

  ErrBadCopyRows='InsertAndCopyRowsia kutsuttiin epäkelvoilla parametreilla';
  ErrInvalidSheetNo='Taulukkonumero "%d" on epäkelpo. Numeron pitää olla %d:n ja %d:n välillä';

  ErrBadRowCount='ROW-tietueen numero ei ole sama kuin solujen lukumäärä';

  ErrEscherNotLoaded='Escher-tietue ei ole kokonaan ladattu';
  ErrLoadingEscher='Virhe ladattaessa Escher-tietuetta';
  ErrBStroreDuplicated='Virhe ladattaessa Escher-tietuetta. BStorella on kaksoiskappale';
  ErrDgDuplicated='Virhe ladattaessa Escher-tietuetta. Dg:lla on kaksoiskappale';
  ErrDggDuplicated='Virhe ladattaessa Escher-tietuetta. Dgg:lla on kaksoiskappale';
  ErrsolverDuplicated='Virhe ladattaessa Escher-tietuetta. Solver containerilla on kaksoiskappale';

  ErrChangingEscher='Virhe käsitellessä Escher-tietuetta.';

  ErrInternal='FlexCel: Logiikkavirhe';

  ErrCantCopyPictFmla='Laskentakaavioon upotettua OLE-objektia ei voi kopioida';

  ErrInvalidErrStr='Epäkelpo solun virhekoodi: "%s"';
  ErrInvalidCellValue='Epäkelpo solun arvo: "%s"';

  ErrCantWriteToFile='Tiedostoon "%s" kirjoittaminen epäonnistui. Tarkista, ettei tiedosto ole toisen käyttäjän käytössä';

  ErrShrFmlaNotFound='Jaettua kaavaa ei löydy';

  //Strings
  ErrInvalidStrLenLength='StrLenLengthin pitää olla 1 tai 2';
  ErrInvalidStringRecord='Epäkelpo merkkijonotietue';

  ErrNotImplemented='Tiedostossa on tyypiltään implementoimaton tietue: %s';

  BaseSheetName='Taulukko';

  ErrNoDataSet='Tietojoukkoa ei ole osoitettu';
  ErrReportNotFound='Raporttia ei löytynyt: %s';
  ErrTooManyPageBreaks='Taulukossa on liian monta manuaalista sivunvaihtoa';

  ErrInvalidRow='Epäkelpo rivi (%d)';
  ErrInvalidCol='Epäkelpo sarake (%d)';

  ErrXlsIndexOutBounds='Indeksi "%d" ominaisuudessa "%s" ei ole välillä %d-%d';

  ErrFileIsPasswordProtected='Tiedosto on suojattu salasanalla';

  ErrNotAString='Odotettiin merkkijono-tyyppiä';
  ErrUnexpectedEof='Kaava loppuu odottamattomasti: "%s"';
  ErrUnexpectedChar='Odottamaton merkki "%s" paikalla %d kaavassa "%s"';
  ErrUnterminatedString='Päättämätön merkkijono kaavassa "%s"';
  ErrMissingParen='Kaavasta "%s" puuttuu "sulku kiinni"-merkki';
  ErrFormulaTooLong='Liian pitkä kaava: "%s"';
  ErrUnexpectedId='Odottamaton tunniste "%s" kaavassa "%s"';
  ErrFunctionNotFound='Funktiota "%s" ei löydy kaavasta "%s"';
  ErrInvalidNumberOfParams='Funktiota "%s" on kutsuttu epäkelvolla määrällä parametreja. Odotettu parametrien määrä: %d, kutsun parametrien määrä: %d';
  ErrFormulaInvalid='Kaavaa "%s" ei voi laskea';
  ErrFormulaStart='Kaavan pitää alkaa "="-merkillä: "%s"';

  ErrHiddenSheetSelected='Tiedoston tallentamiseksi on valittava näkyvä taulukko';
  ErrNoSheetVisible='Tiedostossa ei ole näkyviä taulukoita';

  ErrCantDeleteSheetWithMacros='Makroja sisältävän tiedoston taulukkoa ei voi poistaa';



