  ErrFileIsNotXLS='Fichier "%s" non-valide';
  ErrCantReadFile='Impossible de lire le fichier "%s"';
  ErrExcelInvalid= 'Erreur lors de la lecture du fichier Excel. Fichier non-valide';
  ErrCantWriteOutput='Impossible de créer le fichier de résultats "%s"';
  ErrCantWrite='Erreur lors de l''écriture du fichier de résultats';

  ErrFileNotFound='Fichier "%s" non trouvé';
  ErrStreamNotFound='Stream "%s" non trouvé';

  ErrExtRefsNotSupported='Références externes vers un autre livre ne sont pas supportées par FlexCel';

  ErrWrongExcelRecord='Enregistrement identifié par 0x%x est non-valide';

  ErrBadToken='Erreur lors de la lecture de la formule, le symbole Id: 0x%2x n''est pas supporté';
  ErrBadFormula='Formule à la ligne %d, colonne %d n''est pas supportée. Symbole Id: 0x%2x';
  ErrBadName='Erreur dans le nom de la feuille: "%s". Symbole Id: 0x%2x';
  ErrBadCF='Format conditionnel erronné. Symbole Id: 0x%2x';
  ErrBadChartFormula='Erreur dans une formule graphique. Symbole Id: 0x%2x';

  Err3DRef='Référence vers une autre feuille dans une formule qui ne le supporte pas';

  ErrReadingRecord='Erreur de lecture d''un enregistrement';

  ErrInvalidVersion='Fichier de canevas a été sauvegardée sous une version Excel incorrecte';

  ErrTooManyEntries= 'Trop d''occurences de ce type d''enregistrement (%d pour un maximum de %d)';
  ErrRecordNotSupported='Canevas contenant un type d''enregistrement non-supporté: %4x';

  ErrSectionNotLoaded='Une section du livre n''est pas chargée';

  ErrInvalidContinue='Tentative d''introduire plus d''un enregistrement CONTINUE au même enregistrement';
  ErrStringTooLarge='Chaine de caractères trop longue';
  ErrInvalidDrawing='Fichier contient un enregistrement graphique non supporté';
  ErrInvalidCF='Enregistrement de format conditionnel non-valide';

  ErrDuplicatedSheetName='Ce nom de feuille existe déjà: %s';

  ErrDupRow='Enregistrement ROW double' ;
  ErrRowMissing='Enregistrement ROW manquant pour la ligne %d';

  ErrBadCopyRows='Arguments non-valides lors de l''appel de InsertAndCopyRows';
  ErrInvalidSheetNo='Numéro de page "%d" non-valide. Doit être entre %d et %d';

  ErrBadRowCount='Numéro de l''enregistrement ROW n''est pas identique à la référence de la cellule';

  ErrEscherNotLoaded='L''enregistrement Escher n''est pas entièrement chargé';
  ErrLoadingEscher='Erreur lors du chargement de l''enregistrement Escher';
  ErrBStroreDuplicated='Erreur lors du chargement de l''enregistrement Escher. BStore dédoublé';
  ErrDgDuplicated='Erreur lors du chargement de l''enregistrement Escher. Dg dédoublé';
  ErrDggDuplicated='Erreur lors du chargement de l''enregistrement Escher. Dgg dédoublé';
  ErrsolverDuplicated='Erreur lors du chargement de l''enregistrement Escher. Duplicated Solver container';

  ErrChangingEscher='Erreur lors du traitement de l''enregistrement Escher.';

  ErrInternal='FlexCel: Erreur de logique';

  ErrCantCopyPictFmla='Impossible de copier un objet OLE inclus dans une feuille';

  ErrInvalidErrStr='Code d''erreur de la cellule non-valide: "%s"';
  ErrInvalidCellValue='Valeur de la cellule non-valide: "%s"';

  ErrCantWriteToFile='Impossible d''écrire dans le fichier "%s". Vérifier qu''il ne soit pas utilisé par un autre utilisateur';

  ErrShrFmlaNotFound='Impossible de trouver la formule partagée';

  //Strings
  ErrInvalidStrLenLength='StrLen Length doit être 1 ou 2';
  ErrInvalidStringRecord='Enregistrement d''une chaine de caractères non-valide';

  ErrNotImplemented='Fichier contenant un type d''enregistrement non implementé: %s';

  BaseSheetName='Feuille';

  ErrNoDataSet='Aucun dataset assigné';
  ErrReportNotFound='Rapport non trouvé: %s';
  ErrTooManyPageBreaks='Trop de sauts de page forcés pour cette feuille';

  ErrInvalidRow='Ligne non valide (%d)';
  ErrInvalidCol='Colonne non válide (%d)';

  ErrXlsIndexOutBounds='L''indice "%d" de la propriété "%s" doit être compris entre %d et %d';

  ErrFileIsPasswordProtected='File is password protected';

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';

