//This file is not yet translated - Now it is :)

  ErrFileIsNotXLS='Die Datei "%s" ist ungültig';
  ErrCantReadFile='Konnte DAtei nicht lesen "%s"';
  ErrExcelInvalid= 'Fehler beim lesen von Excel-Einträgen. Datei ist ungültig';
  ErrCantWriteOutput='Konnte Output-Datei nicht erstellen "%s"';
  ErrCantWrite='Fehler beim schreiben der Output-Datei';

  ErrFileNotFound='Konnte Datei nicht finden "%s"';
  ErrStreamNotFound='Konnte Stream nicht öffnen "%s"';

  ErrExtRefsNotSupported='Externe Referenzen zu anderen workbooks werden nicht unterstützt von FlexCel';

  ErrWrongExcelRecord='Eintrag mit ID 0x%x ist ungültig';

  ErrBadToken='Fehler beim lesen von Formel, Token Id: 0x%2x wird nicht unterstützt';
  ErrBadFormula='Formel in Zeile %d, Spalte %d wird nicht unterstützt. Token Id: 0x%2x';
  ErrBadName='Fehler in Worksheet Name: "%s". Token Id: 0x%2x';
  ErrBadCF='Fehler in "Bedingtem Format". Token Id: 0x%2x';
  ErrBadChartFormula='Fehler in Chart Formel. Token Id: 0x%2x';

  Err3DRef='Eine Referenz zu einem anderen worksheet in einer Formel die dies nicht unterstüzt wurde gefunden.';

  ErrReadingRecord='Fehler beim lesen von Eintrag';

  ErrInvalidVersion='Template Datei ist mit einer ungültigen Excelversion gespeichert worden';

  ErrTooManyEntries= 'Zu viele Möglichkeiten für diese Art von Eintrag (%d von Maximal %d)';
  ErrRecordNotSupported='Template einen nicht unterstützten Eintrag: %4x';

  ErrSectionNotLoaded='Ein Bereich des workbook ist nicht geladen';

  ErrInvalidContinue='Versuche mehr hinzuzufügen als ein CONTINUE Eintrag zum selben Eintrag';
  ErrStringTooLarge='String zu lang';
  ErrInvalidDrawing='Die Datei hat einen nicht unterstützten Bildeintrag';
  ErrInvalidCF='Ungültiger "Bedingte Formatierung"-Eintrag';

  ErrDuplicatedSheetName='Sheet Name existiert schon: %s';

  ErrDupRow='Doppelter ROW Eintrag' ;
  ErrRowMissing='Fehlender ROW Eintrag für Zeile %d';

  ErrBadCopyRows='Ungültige Argumente beim Aufruf von InsertAndCopyRows';
  ErrInvalidSheetNo='Sheet Nummer "%d" ist ungültig. Muss zwischen %d und %d liegen';

  ErrBadRowCount='Nummer des ROW Eintrag ist nicht der gleiche wie die Zellenanzahl';

  ErrEscherNotLoaded='Escher Eintrag nicht komplett geladen';
  ErrLoadingEscher='Fehler beim laden von Escher Eintrag';
  ErrBStroreDuplicated='Fehler beim laden von Escher Eintrag. Doppelt vorhander BStore';
  ErrDgDuplicated='Fehler beim laden von Escher Eintrag. Doppelt vorhandes Dg';
  ErrDggDuplicated='Fehler beim laden von Escher Eintrag. Doppelt vorhandenes Dgg';
  ErrsolverDuplicated='Fehler beim Laden von Escher Eintrag. Doppelt vorhandener Solver container';

  ErrChangingEscher='Fehler beim bearbeiten von Escher Eintrag';

  ErrInternal='FlexCel: Logischer Fehler';

  ErrCantCopyPictFmla='Konnte in Sheet eingebettete OLE objekte nicht kopieren';

  ErrInvalidErrStr='Ungültiger Zellen-Fehlercode: "%s"';
  ErrInvalidCellValue='Üngültiger Zellenwert: "%s"';

  ErrCantWriteToFile='Konnte nicht in Datei "%s" schreiben. Prüfen Sie ob kein anderer User sie geöffnet hat';

  ErrShrFmlaNotFound='Konnte Shared Formula nicht finden';

  //Strings
  ErrInvalidStrLenLength='StrLenLength sollte 1 oder 2 sein';
  ErrInvalidStringRecord='Ungültiger String Eintrag';

  ErrNotImplemented='Diese Datei hat eine nicht unterstützte Art von Eintrag: %s';

  BaseSheetName='Sheet';

  ErrNoDataSet='Kein Datensatz zugeordnet';
  ErrReportNotFound='Report nicht gefunden: %s';
  ErrTooManyPageBreaks='Zu viele manuellen Seitenumbrüche für dieses Sheet';

  ErrInvalidRow='Ungültige Zeile (%d)';
  ErrInvalidCol='Ungültige Spalte (%d)';

  ErrXlsIndexOutBounds='Der index "%d" der Eigenschaft "%s" ist nicht im Bereich %d-%d';

  ErrFileIsPasswordProtected='Datei ist Passwortgeschützt';

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';

