  ErrFileIsNotXLS='Il file "%s" non è valido';
  ErrCantReadFile='Impossibile leggere il file "%s"';
  ErrExcelInvalid= 'Errore di lettura nel registro Excel. File non valido';
  ErrCantWriteOutput='Impossibile creare il file "%s"';
  ErrCantWrite='Errore di scrittura nel file di uscita';

  ErrFileNotFound='Impossibile trovare il file "%s"';
  ErrStreamNotFound='Impossibile aprire lo Stream "%s"';

  ErrExtRefsNotSupported='I riferimenti a un altro libro non sono supportati da FlexCel';

  ErrWrongExcelRecord='Il record con ID 0x%x non è valido';

  ErrBadToken='Errore nella formula, Token Id: 0x%2x non supportato';
  ErrBadFormula='La formula nella fila %d, colonna %d non è supportata. Token Id: 0x%2x';
  ErrBadName='Errore nel nome del foglio di calcolo: "%s". Token Id: 0x%2x';
  ErrBadCF='Errore nel formato condizionale. Token Id: 0x%2x';
  ErrBadChartFormula='Errore nella formula grafica. Token Id: 0x%2x';

  Err3DRef='Trovato un riferimento a un altro foglio riguardo una formula non supportata';

  ErrReadingRecord='Errore nella lettura del registro';

  ErrInvalidVersion='Il file Template è stato salvato con una versione di Excel non valida';

  ErrTooManyEntries= 'Troppe entrate per questo tipo di registro (%d per un massimo di %d)';
  ErrRecordNotSupported='Il file contiene un tipo di registro non supportato: %4x';

  ErrSectionNotLoaded='Una sezione del foglio di calcolo non è stata caricata';

  ErrInvalidContinue='Tentativo di introdurre più di un campo di tipo CONTINUE nello stesso registro';
  ErrStringTooLarge='Stringa troppo grande';
  ErrInvalidDrawing='File con un registro di disegno non supportato';
  ErrInvalidCF='Formato condizionale non valido';

  ErrDuplicatedSheetName='Nome del foglio già esistente: %s';

  ErrDupRow='Registro Row già esistente' ;
  ErrRowMissing='Manca il registro ROW per la fila %d';

  ErrBadCopyRows='Chiamata a InsertAndCopyRows con argomenti non validi';
  ErrInvalidSheetNo='Numero di pagina "%d" non valido. Deve essere compreso tra %d e %d';

  ErrBadRowCount='Il numero di registri ROW non coincide con il totale delle celle';

  ErrEscherNotLoaded='Il record Escher non è stato caricato completamente';
  ErrLoadingEscher='Errore nel caricare il registro Escher';
  ErrBStroreDuplicated='Errore nel caricare il registro Escher. BStore già esistente';
  ErrDgDuplicated='Errore nel caricare il registro Escher. Dg già esistente';
  ErrDggDuplicated='Errore nel caricare il registro Escher. Dgg già esistente';
  ErrsolverDuplicated='Errore nel caricare il registro Escher. Solver container già esistente';

  ErrChangingEscher='Errore nell''elaborazione di un registro Escher';

  ErrInternal='FlexCel: Errore logico';

  ErrCantCopyPictFmla='Non si possono copiare oggetti OLE inclusi in un foglio';

  ErrInvalidErrStr='Codice d''errore delle cella non valido: "%s"';
  ErrInvalidCellValue='Valore della cella non valido: "%s"';

  ErrCantWriteToFile='Errore di scrittura nel file "%s". Verificare che non sia utilizzato da un altro utente';

  ErrShrFmlaNotFound='Non si può trovare la Shared Formula corrispondente a una formula';

  //Strings
  ErrInvalidStrLenLength='StrLenLength deve essere 1 o 2';
  ErrInvalidStringRecord='String record non valido';

  ErrNotImplemented='Questo file contiene un tipo di registro non implementato: %s';

  BaseSheetName='Foglio';

  ErrNoDataSet='Nessun dataset assegnato';
  ErrReportNotFound='Impossibile trovare il report %s';
  ErrTooManyPageBreaks='Esistono troppi salti di pagina manuali per questo foglio';

  ErrInvalidRow='Fila non valida (%d)';
  ErrInvalidCol='Colonna non valida (%d)';

  ErrXlsIndexOutBounds='L''indice "%d" della proprietà "%s" non è contenuto nell''intervallo %d-%d';

  ErrFileIsPasswordProtected='File is password protected';

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';

