  ErrFileIsNotXLS='O arquivo "%s" é inválido'; 
  ErrCantReadFile='Não é possível ler o arquivo "%s"'; 
  ErrExcelInvalid= 'Erro ao ler os registros do Excel. Arquivo inválido'; 
  ErrCantWriteOutput='Impossível criar o arquivo de saída "%s"'; //'Can''t create output file "%s"';
  ErrCantWrite='Erro ao gravar o arquivo de saída'; //'Error writing output file';

  ErrFileNotFound='Impossível encontrar o arquivo "%s"'; //'Can''t find file "%s"';
  ErrStreamNotFound='Não é possível abrir o Fluxo "%s"'; 
  ErrExtRefsNotSupported='As referências externas a outro Workbook não são suportadas por FlexCel'; 

  ErrWrongExcelRecord='O registro com ID 0x%x é inválido'; 

  ErrBadToken='Erro ao ler a fórmula, o Toekn ID: 0x%2x não é suportado'; 
  ErrBadFormula='A fórmula na Linha %d, Coluna %d não é suportada. Token ID: 0x%2x'; 
  ErrBadName='Erro na planilha: %s. Token ID: 0x%2x'; 
  ErrBadCF='Formato condicional ruim. Token ID: 0x%2x'; 
  ErrBadChartFormula='Erro na fórmula do Gráfico. Token ID: 0x%2x'; 

  Err3DRef='Encontrada uma referência para outra planilha numa fórmula que não suporta isto'; 

  ErrReadingRecord='Erro ao ler o registro'; 

  ErrInvalidVersion='O arquivo de modelo foi salvo com uma versão inválida do Excel'; 

  ErrTooManyEntries= 'Existem muitas entradas para este tipo de registro (%d para um máximo de %s)'; 
  ErrRecordNotSupported='O modelo contém um registro não suportado: %4x'; 

  ErrSectionNotLoaded='Uma seção do Workbook não foi carregada'; 

  ErrInvalidContinue='Tentativa de adicionar mais de um registro CONTÍNUO para o mesmo registro'; 
  ErrStringTooLarge='String muito grande'; 
  ErrInvalidDrawing='O arquivo tem um registro de desenho não suportado'; 
  ErrInvalidCF='Formato de registro condicinal inválido'; 

  ErrDuplicatedSheetName='O nome da página já existe'; 

  ErrDupRow='Registro de LINHA duplicado'; 
  ErrRowMissing='Não existe o registro de LINHA para a linha %d'; 

  ErrBadCopyRows='Argumento inválido para chamar InsertAndCopyRows'; 
  ErrInvalidSheetNo='Número de folha %d inválido. deve ser entre %d e %d'; 

  ErrBadRowCount='O número do registro de LINHA não é o mesmo que o contador de células'; 

  ErrEscherNotLoaded='O registro Escher não está totalmente carregado'; 
  ErrLoadingEscher='Erro ao carregar o registro Escher'; 
  ErrBStroreDuplicated='Erro ao carregar o registro Escher. BStore duplicado'; 
  ErrDgDuplicated='Erro ao carregar o registro Escher. Dg duplicado'; 
  ErrDggDuplicated='Erro ao carregar o registro Escher. Dgg duplicado'; 
  ErrsolverDuplicated='Erro ao carregar o registro Escher. Solver container duplicado'; 

  ErrChangingEscher='Erro ao processar o registro Escher'; 

  ErrInternal='FlexCel: Erro de lógica'; 

  ErrCantCopyPictFmla='Impossível copiar objetos OLE embutidos na planilha'; 

  ErrInvalidErrStr='Célula inválida código do erro: %s'; 
  ErrInvalidCellValue='Valor de célula inválido: %s'; 

  ErrCantWriteToFile='Não é possível gravar no arquivo "%s". Verifique se se ele não está sendo usado por outro usuário'; 

  ErrShrFmlaNotFound='Não é possível encontrar a Fórmula Compartilhada'; 

  //Strings
  ErrInvalidStrLenLength='StrLenLenght deve ser 1 ou 2'; 
  ErrInvalidStringRecord='Registro de String inválido'; 
  ErrNotImplemented='Este arquivo tem um tipo de registro não implementado: %s'; 

  BaseSheetName='Plan'; 

  ErrNoDataSet='Não existe nenhum dataset assinalado'; 
  ErrReportNotFound='Relatório não encontrado: %s'; 
  ErrTooManyPageBreaks='Excesso de quebras de página manual para esta planilha'; 

  ErrInvalidRow='Linha inválida (%d)'; 
  ErrInvalidCol='Coluna inválida (%d)'; 

  ErrXlsIndexOutBounds='O índice "%d" da propriedade "%s" não está na faixa %d-%d'; 

  ErrFileIsPasswordProtected='O arquivo é protegido por senha'; 

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';

