  ErrFileIsNotXLS='Файл "%s" имеет неверный формат';
  ErrCantReadFile='Не могу прочитать файл "%s"';
  ErrExcelInvalid= 'Ошибка чтения записей Excel. Файл неверен';
  ErrCantWriteOutput='Не могу создать выходной файл "%s"';
  ErrCantWrite='Ошибка при записи выходного файла';

  ErrFileNotFound='Не могу найти файл "%s"';
  ErrStreamNotFound='Не могу открыть поток "%s"';

  ErrExtRefsNotSupported='Внешние ссылки на другую книгу не поддерживаются FlexCel';

  ErrWrongExcelRecord='Запись с ID 0x%x ошибочна';

  ErrBadToken='Ошибка чтения формулы, Token Id: 0x%2x не поддерживается';
  ErrBadFormula='Формула в строке %d, столбце %d не поддерживается. Token Id: 0x%2x';
  ErrBadName='Ошибка в имени листа: "%s". Token Id: 0x%2x';
  ErrBadCF='Неверный условный формат. Token Id: 0x%2x';
  ErrBadChartFormula='Ошибка в формуле диаграммы. Token Id: 0x%2x';

  Err3DRef='Обнаружена ссылка на другой лист в формуле, которая не поддерживает эту воможность';

  ErrReadingRecord='Ошибка чтения записи';

  ErrInvalidVersion='Файл шаблона был сохранен не поддерживаемой версией Excel ';

  ErrTooManyEntries= 'Слишком много элементов для этого вида записи (%d из максимум %d)';
  ErrRecordNotSupported='Шаблон содержит не поддерживаемую запись: %4x';

  ErrSectionNotLoaded='Раздел книги не загружен';

  ErrInvalidContinue='Попытка добавить более одной записи CONTINUE в ту же запись';
  ErrStringTooLarge='Слишком длинная строка';
  ErrInvalidDrawing='Файл содержит не поддерживаемую запись рисования';
  ErrInvalidCF='Неверная запись с условным форматом';

  ErrDuplicatedSheetName='Имя листа уже существует: %s';

  ErrDupRow='Дубликат записи ROW' ;
  ErrRowMissing='Пропущена запись ROW для строки %d';

  ErrBadCopyRows='Неверные аргументы для вызова InsertAndCopyRows';
  ErrInvalidSheetNo='Номер листа "%d" неверен. Должен быть от %d до %d';

  ErrBadRowCount='Число записей ROW не равно числу строк';

  ErrEscherNotLoaded='Запись Escher загружена не полностью';
  ErrLoadingEscher='Ошибка загрузки записи Escher';
  ErrBStroreDuplicated='Ошибка загрузки записи Escher. Дубликат BStore';
  ErrDgDuplicated='Ошибка загрузки записи Escher. Дубликат Dg';
  ErrDggDuplicated='Ошибка загрузки записи Escher. Дубликат Dgg';
  ErrsolverDuplicated='Ошибка загрузки записи Escher. Дубликат контейнера Solver';

  ErrChangingEscher='Ошибка обработки записи Escher';

  ErrInternal='FlexCel: Логическая ошибка';

  ErrCantCopyPictFmla='Не могу скопировать объекты OLE, встроенные в лист';

  ErrInvalidErrStr='Код ошибки неверной ячейки: "%s"';
  ErrInvalidCellValue='Неверное значение ячейки: "%s"';

  ErrCantWriteToFile='Не могу записать файл "%s". Убедитесь, что он не занят другим пользователем';

  ErrShrFmlaNotFound='Не могу найти Shared Formula';

  //Strings
  ErrInvalidStrLenLength='Значение StrLenLength должно быть 1 или 2';
  ErrInvalidStringRecord='Неверная строковая запись';

  ErrNotImplemented='Файл содержит не поддерживаемый вид записей: %s';

  BaseSheetName='Лист';

  ErrNoDataSet='Набор данных не назначен';
  ErrReportNotFound='Отчет не найден: %s';
  ErrTooManyPageBreaks='Слишко много ручных разрывов страницы на листе';

  ErrInvalidRow='Неверная строка (%d)';
  ErrInvalidCol='Неверный столбец (%d)';

  ErrXlsIndexOutBounds='Индекс "%d" свойства "%s" вне диапазона %d-%d';

  ErrFileIsPasswordProtected='Файл защищен паролем';

/////
  ErrNotAString='Ожидалась строка';
  ErrUnexpectedEof='Неожиданный конец формулы: "%s"';
  ErrUnexpectedChar='Непредвиденный символ "%s" в позиции %d в формуле: "%s"';
  ErrUnterminatedString='Незаконченная строка в формуле: "%s"';
  ErrMissingParen='Пропущены закрывающие круглые скобки в формуле: "%s"';
  ErrFormulaTooLong='Формула слишком длинная: "%s"';
  ErrUnexpectedId='Непредвиденный идентификатор: "%s" в формуле "%s"';
  ErrFunctionNotFound='Функция не найдена: "%s" в формуле "%s"';
  ErrInvalidNumberOfParams='Неверное число параметров в функции "%s": Пропущен %d и найден %d';
  ErrFormulaInvalid='Формула не может быть вычислена: "%s"';
  ErrFormulaStart='Формула должна начинаться с "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';

  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';



