  ErrFileIsNotXLS='Fisierul "%s" este invalid';
  ErrCantReadFile='Nu pot citi fisierul "%s"';
  ErrExcelInvalid= 'Eroare la citirea inregistrarilor Excel. Fisier invalid';
  ErrCantWriteOutput='Nu pot crea fisierul "%s"';
  ErrCantWrite='Eroare la scrierea fisierului de iesire';

  ErrFileNotFound='Nu gasesc fisierul "%s"';
  ErrStreamNotFound='Nu pot deschide stream-ul "%s"';

  ErrExtRefsNotSupported='Referinte externe catre alte seturi de foi calcul nu sunt suportate de FlexCel';

  ErrWrongExcelRecord='Inregistrarea cu ID 0x%x este invalida';

  ErrBadToken='Eroare la citirea formulei, elementul Id: 0x%2x nu este suportat';
  ErrBadFormula='Formula din Randul %d, coloana %d nu este suportata. Element Id: 0x%2x';
  ErrBadName='Eroare in foaia de calcul denumita: "%s". Element Id: 0x%2x';
  ErrBadCF='Format conditional invalid. Element Id: 0x%2x';
  ErrBadChartFormula='Eroare in formula Hartii. Element Id: 0x%2x';

  Err3DRef='S-a gasit o referinta la o alta foaie de calcul sau formula ce nu sunt suportate';

  ErrReadingRecord='Eroare la citirea inregistrarii';

  ErrInvalidVersion='Fisierul Tipar (template) este salvat sub o versiune Excel invalida';

  ErrTooManyEntries= 'Prea multe date pt acest tip de inregistrare (%d peste maximumul de %d)';
  ErrRecordNotSupported='Tiparul (template) contine o inregistrare ce nu este suportata: %4x';

  ErrSectionNotLoaded='O sectiune a setului de foi calcul nu este incarcata';

  ErrInvalidContinue='Ati incercat sa adaugati mai mult de o inregistrare CONTINUA in aceeasi inregistrare';
  ErrStringTooLarge='Sir de caractere prea mare (propozitia prea lunga)';
  ErrInvalidDrawing='Fisierul are o inregistrare grafica ce nu este suportata';
  ErrInvalidCF='Format conditional al inregistrarii - invalid';

  ErrDuplicatedSheetName='Exista o foaie cu acelasi nume deja: %s';

  ErrDupRow='Rand cu inregistrare duplicat (dublata)' ;
  ErrRowMissing='Lipseste inregistrarea pt randul %d';

  ErrBadCopyRows='Apelarea InsertAndCopyRows are argumente invalide';
  ErrInvalidSheetNo='Numar invalid al foii de calcul "%d". Trebuie sa fie intre %d si %d';

  ErrBadRowCount='Numarul de inregistrari pe Rand nu este acelasi cu numarul de celule';

  ErrEscherNotLoaded='Inregistrarea Escher nu este incarcata total';
  ErrLoadingEscher='Eroare la incarcarea inregistrarii Escher';
  ErrBStroreDuplicated='Eroare la incarcarea inregistrarii Escher. BStore duplicat';
  ErrDgDuplicated='Eroare la incarcarea inregistrarii Escher. Dg duplicat';
  ErrDggDuplicated='Eroare la incarcarea inregistrarii Escher. Dgg duplicat';
  ErrsolverDuplicated='Eroare la incarcarea inregistrarii Escher. Containerul Solver este duplicat';

  ErrChangingEscher='Eroare la procesarea inregistrarii Escher';

  ErrInternal='FlexCel: Eroare logica !';

  ErrCantCopyPictFmla='Nu pot copia obiectele OLE din foaia de calcul';

  ErrInvalidErrStr='Invalid cell error code: "%s"';
  ErrInvalidCellValue='Invalid cell value: "%s"';

  ErrCantWriteToFile='Nu pot scrie in fisierul "%s". Verificati daca nu este deja deschis';

  ErrShrFmlaNotFound='Nu pot gasi formula comuna (shared)';

  //Strings
  ErrInvalidStrLenLength='StrLenLength trebuie sa fie 1 sau 2';
  ErrInvalidStringRecord='Inregistrare de tip sir de caractere invalida';

  ErrNotImplemented='Acest fisier nu are implementat tipul de inregistrare: %s';

  BaseSheetName='Foaia';

  ErrNoDataSet='Nu s-a asignat un Dataset';
  ErrReportNotFound='Raportul nu exista: %s';
  ErrTooManyPageBreaks='Prea multe ruperi de pagina manuale (Page Break) pt aceasta pagina';

  ErrInvalidRow='Rand invalid (%d)';
  ErrInvalidCol='Coloana invalida (%d)';

  ErrXlsIndexOutBounds='Indexul "%d" proprietatii "%s" nu este in domeniul %d-%d';

  ErrFileIsPasswordProtected='Fisierul este protejat prin parola';

  ErrNotAString='String expected';
  ErrUnexpectedEof='Unexpected end of formula: "%s"';
  ErrUnexpectedChar='Unexpected char "%s" at pos %d on formula: "%s"';
  ErrUnterminatedString='Unterminated string on formula: "%s"';
  ErrMissingParen='Missing closing parentheses on formula: "%s"';
  ErrFormulaTooLong='Formula too long: "%s"';
  ErrUnexpectedId='Unexpected Identifier: "%s" on formula "%s"';
  ErrFunctionNotFound='Function not found: "%s" on formula "%s"';
  ErrInvalidNumberOfParams='Invalid number of parameters to function "%s": Expected %d and found %d';
  ErrFormulaInvalid='Formula can''t be evaluated: "%s"';
  ErrFormulaStart='Formula must start with "=": "%s"';

  ErrHiddenSheetSelected='To save this file, you must select a visible sheet';
  ErrNoSheetVisible='There are not visible sheets on the file';


  ErrCantDeleteSheetWithMacros='Can''t delete a sheet on a file containing macros';

  ErrInvalidSheet='Invalid sheet: %s';