  ErrFileIsNotXLS='El archivo "%s" no es válido';
  ErrCantReadFile='No se puede leer el archivo "%s"';
  ErrExcelInvalid= 'Error al leer los registros del archivo Excel';
  ErrCantWriteOutput='No se puede crear el archivo "%s"';
  ErrCantWrite='Error al escribir en el archivo de salida';

  ErrFileNotFound='No se puede encontrar el archivo "%s"';
  ErrStreamNotFound='No se puede abrir el Stream "%s"';

  ErrExtRefsNotSupported='Las referencias a otro libro no estan soportadas por FlexCel';

  ErrWrongExcelRecord='El record con ID 0x%x es erróneo';

  ErrBadToken='Error en la fórmula, Token Id: 0x%2x no está soportado';
  ErrBadFormula='La fórmula en la fila %d, columna %d no está soportada. Token Id: 0x%2x';
  ErrBadName='Error el Nombre de la hoja de calculo: "%s". Token Id: 0x%2x';
  ErrBadCF='Error el Formato condicional. Token Id: 0x%2x';
  ErrBadChartFormula='Error en la fórmula de un gráfico. Token Id: 0x%2x';

  Err3DRef='Se ha encontrado una referencia a otra pagina en una formula que no lo soporta';

  ErrReadingRecord='Error al leer registro';

  ErrInvalidVersion='El archivo Template está grabado con una versión inválida de Excel';

  ErrTooManyEntries= 'Demasiadas entradas para un tipo de registro (%d para un máximo de %d)';
  ErrRecordNotSupported='El archivo tiene un tipo de registro no soportado: %4x';

  ErrSectionNotLoaded='Una sección de la hoja de cálculo no ha sido cargada';

  ErrInvalidContinue='Se esta intentando introducir mas de un record de tipo CONTINUE en el mismo registro';
  ErrStringTooLarge='La planilla tiene una cadena demasiado grande';
  ErrInvalidDrawing='El archivo tiene un registro de dibujo no soportado';
  ErrInvalidCF='Formato condicional inválido';

  ErrDuplicatedSheetName='Nombre de hoja duplicado: %s';

  ErrDupRow='Registro Row duplicado' ;
  ErrRowMissing='Falta el registro ROW para la fila %d';

  ErrBadCopyRows='Llamada a InsertAndCopyRows con argumentos invalidos';
  ErrInvalidSheetNo='Número de pagina "%d" inválido. Debe estar entre %d y %d';

  ErrBadRowCount='El número de registros ROW no coincide con el total de celdas';

  ErrEscherNotLoaded='El record Escher no ha sido completamente cargado';
  ErrLoadingEscher='Error al cargar un registro Escher';
  ErrBStroreDuplicated='Error al cargar registro Escher. BStore duplicado';
  ErrDgDuplicated='Error al cargar registro Escher. Dg duplicado';
  ErrDggDuplicated='Error al cargar registro Escher. Dgg duplicado';
  ErrsolverDuplicated='Error al cargar registro Escher. Solver container duplicado';

  ErrChangingEscher='Error al procesar un registro Escher';

  ErrInternal='FlexCel: Error lógico';

  ErrCantCopyPictFmla='No se puede copiar objetos OLE incrustados en una Hoja';

  ErrInvalidErrStr='Codigo de error de la celda inválido: "%s"';
  ErrInvalidCellValue='Valor de la celda inválido: "%s"';

  ErrCantWriteToFile='Error al escribir en el archivo "%s". Verifique que no esté en uso por otro usuario';

  ErrShrFmlaNotFound='No se puede encontrar la Shared Formula correspondiente a una formula';

  //Strings
  ErrInvalidStrLenLength='StrLenLength debe ser 1 o 2';
  ErrInvalidStringRecord='String record inválido';

  ErrNotImplemented='Este archivo tiene un tipo de registro no implementado: %s';

  BaseSheetName='Hoja';

  ErrNoDataSet='No hay dataset asignado';
  ErrReportNotFound='No se puede encontrar el reporte %s';
  ErrTooManyPageBreaks='Hay demasiados saltos de página manuales para esta hoja';

  ErrInvalidRow='Fila no válida (%d)';
  ErrInvalidCol='Columna no válida (%d)';

  ErrXlsIndexOutBounds='El indice "%d" de la propiedad "%s" no está en el rango %d-%d';

  ErrFileIsPasswordProtected='El archivo está protegido por contraseña';

  ErrNotAString='Se esperaba una String';
  ErrUnexpectedEof='Inesperado final de la fórmula: "%s"';
  ErrUnexpectedChar='Carácter inesperado "%s" en la posición %d de la fórmula: "%s"';
  ErrUnterminatedString='String sin terminar en la fórmula: "%s"';
  ErrMissingParen='Falta un paréntesis de cierre en la fórmula: "%s"';
  ErrFormulaTooLong='Fórmula demasiado larga: "%s"';
  ErrUnexpectedId='Identificador no esperado: "%s" en la fórmula "%s"';
  ErrFunctionNotFound='Función no encontrada: "%s" en la fórmula "%s"';
  ErrInvalidNumberOfParams='Número de parámetros inválido para la función "%s": se esperaba %d y se encontraron %d';
  ErrFormulaInvalid='No se puede evaluar la fórmula: "%s"';
  ErrFormulaStart='La fórmula debe empezar con "=": "%s"';

  ErrHiddenSheetSelected='Para grabar el archivo debe seleccionar una hoja visible';
  ErrNoSheetVisible='No hay ninguna hoja visible en el archivo';

  ErrCantDeleteSheetWithMacros='No se pueden borrar hojas en archivos que contienen macros';

  ErrInvalidSheet='Hoja inválida: %s';
