//------------------------------------------------------------------------------
//  This file was introduce to avoid the need to get the version no from the
//  executable.  Virus scanners seem to be having problems with the API call
//  to get the version number.
//------------------------------------------------------------------------------
const
   VERMAJOR;
   VERMINOR;
   VERRELEASE;
   VERBUILD;
   VERYEAR;