
#define About_business_norm_percentages	1001
#define About_the_Full_and_Simplified_methods	1002
#define Accomplish_CashManager	1003
#define AccPac_for_Windows	1004
#define Accrual_journals	1005
#define Adding_a_payee	1007
#define Adding_and_maintaining_users	1008
#define Adding_cheque_ranges	1009
#define Adding_divisions	1010
#define Adding_historical_data	1011
#define Adding_initial_unpresented_cheques	1012
#define Adding_initial_unpresented_deposits	1013
#define Adding_sub_groups	1014
#define Adding_tasks	1015
#define Adding_unpresented_cheques	1016
#define Adding_unpresented_deposits	1017
#define Analysis_coding_New_Zealand_	1018
#define Appendix_1_Accounting_system_interfaces	1019
#define Assigning_divisions	1021
#define Assigning_divisions_by_merging_charts_of_accounts	1022
#define Assigning_report_groups	1024
#define Assigning_report_groups_by_merging_charts_of_accounts	1025
#define Assigning_sub_groups	1026
#define Assigning_sub_groups_by_merging_charts_of_accounts	1027
#define Assigning_the_practice_contact	1028
#define Attache_BP	1029
#define Automatic_tasks	1030
#define Backing_up_your_data	1031
#define Balance_sheet_report	1032
#define Balancing_transactions	1033
#define Bank_Accounts	1034
#define Bank_reconciliation_report	1035
#define BankLink_Connect_Security	1037
#define BankLink_toolbar_buttons	1039
#define BGL_Simple_Fund	1040
#define BNotes_clients	1041
#define Budget_remaining	1042
#define Budget_report	1043
#define Business_norms_percentages_report	1044
#define Cancelling_unpresented_cheques	1045
#define Cancelling_unpresented_deposits	1046
#define CaseWare	1047
#define Cash_Flow_12_months_actual	1048
#define Cash_Flow_12_months_actual_or_budget	1049
#define Cash_Flow_Actual	1050
#define Cash_Flow_Actual_and_budget	1051
#define Cash_Flow_Actual_budget_and_variance	1052
#define Cash_Flow_Custom	1053
#define Cash_Flow_reports	1054
#define Cash_Flow_This_year_last_year_and_variance	1055
#define Cash_journals	1056
#define Changing_and_hiding_report_titles_and_headings	1057
#define Changing_the_Code_Entries_Screen_layout	1058
#define Changing_the_financial_year_start_date	1059
#define Changing_the_way_the_Client_Manager_displays_data	1060
#define Chapter_1_Opening_BankLink	1061
#define Chapter_10_Journals	1062
#define Chapter_11_Accounting_for_stock	1063
#define Chapter_12_Setting_up_reporting	1064
#define Chapter_13_Producing_reports	1065
#define Chapter_14_Producing_graphs	1066
#define Chapter_15_Year_End_Balances	1067
#define Chapter_16_Transferring_coded_data_to_your_accounting_system	1068
#define Chapter_2_Clients_charts_of_account_and_bank_accounts	1069
#define Chapter_3_Start_coding	1070
#define Chapter_4_Dissecting	1071
#define Chapter_5_Memorisations	1072
#define Chapter_6_Unpresented_items	1073
#define Chapter_8_Coding_reports_and_BNotes	1075
#define Chapter_9_Budgets	1076
#define Chapter_A1_Installing_BankLink	1077
#define Chapter_A2_Off_site_clients	1078
#define Chapter_A3_Upgrading_BankLink_from_the_website	1079
#define Chapter_A4_Setting_up_GST_Australia_	1080
#define Chapter_A4_Setting_up_GST_NZ	1081
#define Chapter_A5_Creating_client_files_and_attaching_bank_accounts 	1082
#define Chapter_A6_Security	1083
#define Chapter_A7_Downloading_and_purging_data	1084
#define Chapter_A8_Scheduled_reports	1085
#define Chapter_A9_The_System_menu	1086
#define Chart_look_up	1087
#define Checking_for_inactive_accounts	1090
#define Checking_the_bank_balance	1091
#define Client_File_Access_Report	1093
#define Client_file_information	1094
#define Client_file_toolbar_buttons	1095
#define Client_files_and_bank_accounts	1096
#define Clients_and_bank_accounts	1098
#define Closing_a_client_file	1099
#define Closing_tasks	1100
#define Code_Entry_toolbar_buttons	1101
#define Coded_transaction	1102
#define Coding	1103
#define Coding_by_payee	1104
#define Coding_by_payee_in_a_dissection	1105
#define Coding_GST_Australia_	1106
#define Coding_GST_New_Zealand_	1107
#define Comments	1108
#define Comparto	1109
#define Concept_2000_Also_known_as_Concept_Cash_Manager_2000_	1110
#define Configure_columns	1111
#define Copying_a_chart_from_AccPac_into_BankLink	1112
#define Copying_a_chart_from_BGL_Simple_Fund_into_BankLink	1114
#define Copying_a_chart_from_CaseWare_into_BankLink	1115
#define Copying_a_chart_from_CashManager_into_BankLink	1116
#define Copying_a_chart_from_Comparto_into_BankLink	1117
#define Copying_a_chart_from_Concept_2000_into_BankLink	1118
#define Copying_a_chart_from_HandiLedger_into_BankLink	1119
#define Copying_a_chart_from_Intech_into_BankLink	1120
#define Copying_a_chart_from_M_GL_into_BankLink	1121
#define Copying_a_chart_from_MYOB_Accounting_into_BankLink	1122
#define Copying_a_chart_from_MYOB_AO_into_BankLink_Australia_	1123
#define Copying_a_chart_from_Attache_BP_into_BankLink	1113
#define Copying_a_chart_from_PA_into_BankLink_Australia_	1125
#define Copying_a_chart_from_PA_into_BankLink_New_Zealand_	1126
#define Copying_a_chart_from_QuickBooks_into_BankLink	1127
#define Copying_a_chart_from_Solution_6_Accounts_into_BankLink	1128
#define Copying_a_chart_from_Solution_6_into_BankLink_Australia_	1129
#define Copying_a_chart_from_Tax_Assistant_into_BankLink	1131
#define Copying_divisions_from_another_client	1133
#define Copying_report_titles_and_headings_from_another_client	1134
#define Copying_sub_groups_from_another_client	1135
#define Create_a_new_client	1136
#define Creating_a_client_in_BankLink_the_New_Client_Wizard	1137
#define Creating_a_transaction_file_to_send_to_a_client	1138
#define Creating_an_initial_database	1139
#define Creating_an_off_site_BankLink_Connect_client	1140
#define Creating_budgets	1141
#define Creating_sub_headings_by_adding_sub_groups	1142
#define Date_selection_options	1143
#define Default_report_titles_and_headings	1144
#define Delete_a_bank_account_from_a_client_file	1145
#define Delete_a_client	1146
#define Deleting_a_bank_account_from_your_BankLink_system	1147
#define Deleting_a_budget	1148
#define Deleting_a_payee	1149
#define Deleting_and_editing_historical_data	1150
#define Deleting_from_a_chart_of_accounts	1151
#define Deleting_master_memorisations	1152
#define Deleting_tasks	1153
#define Deleting_unpresented_cheques	1154
#define Deleting_unpresented_deposits	1155
#define Direct_link_to_the_main_accounting_system	1156
#define Dissected_transaction_with_notes	1157
#define Divisions	1159
#define Download_Log	1161
#define Downloading	1162
#define Downloading_at_an_off_site_client_using_BankLink_Connect	1163
#define Downloading_with_BankLink_Connect	1165
#define E_mailing_a_transaction_file_to_a_client	1166
#define E_mailing_from_within_BankLink	1167
#define Edit_all_columns_facility	1168
#define Edit_bank_account_details	1169
#define Edit_client_contact_details	1170
#define Editing_a_payee	1171
#define Editing_and_deleting_dissected_transactions	1172
#define Editing_client_details	1173
#define Editing_the_chart_of_accounts	1174
#define Enter_a_code	1175
#define Entering_a_chart_directly_into_BankLink	1176
#define Exception_report	1177
#define Extract_data	1178
#define Favourite_help_topics	1179
#define Filtering_transactions_coded_or_uncoded	1180
#define Finalise_accounting_period_for_GST_purposes	1181
#define Finding_a_transaction	1182
#define Finding_the_workstation_where_a_user_is_logged_in	1183
#define Finding_uncoded_transactions	1184
#define Flagging_transactions	1185
#define From_date_to_date	1186
#define Generating_journals_in_a_future_period	1190
#define Getting_started_with_BankLink_Connect	1192
#define GST_audit_trail_report	1194
#define GST_Journals	1195
#define Generate_scheduled_reports_the_Fax_Set_up_tab	1187
#define Generate_scheduled_reports_the_Options_tab	1188
#define Generate_scheduled_reports_the_Report_Setup_tab	1189
#define GST_overrides_report	1196
#define GST_reconciliation_report	1197
#define GST_report_options	1198
#define GST_Reports	1199
#define GST_Return_GST_101	1200
#define GST_summary_report	1201
#define GST_Template_files	1202
#define Guide_conventions	1203
#define HandiLedger_AU	1204
#define Help_keyboard_shortcuts	1205
#define How_BankLink_populates_the_GST_Calculation_Sheet	1206
#define Importing_a_BNotes_file_into_BankLink	1210
#define INI_file_settings	1211
#define Installing_BankLink_on_a_network	1212
#define Installing_BankLink_on_a_stand_alone_PC	1213
#define Installing_BNotes	1214
#define Intech	1215
#define Integration_with_your_main_accounting_system	1216
#define Interface_to_HandiTax	1217
#define Interface_to_Solution_6_Tax_AU	1218
#define Interface_to_Xlon_Tax_Accounts	1219
#define Introducing_BankLink	1220
#define Key_concepts	1221
#define Key_concepts_Memorisations	1222
#define Keyboard_conventions	1223
#define Keyboard_shortcuts	1224
#define Linking_to_your_accounting_system	1225
#define List_bank_accounts	1226
#define List_bank_accounts_System	1227
#define List_chart_of_accounts	1228
#define List_Client_Report_Options	1229
#define List_Clients_by_Staff_Member	1230
#define List_divisions	1231
#define List_entries	1232
#define List_GST_details	1233
#define List_journals	1234
#define List_memorisations	1236
#define List_missing_cheques_report	1237
#define List_payees	1238
#define List_reports	1239
#define List_sub_groups	1240
#define List_unpresented_items_report	1241
#define M_GL	1242
#define Maintain_Clients	1243
#define Maintaining_client_chart_of_account_information	1244
#define Maintaining_client_files	1245
#define Manual_coding	1246
#define Manually_matching_unpresented_cheques_where_the_amount_differs	1247
#define Manually_matching_unpresented_cheques_where_the_cheque_numbers_differ	1248
#define Master_memorised_entries	1250
#define Matching_unpresented_cheques	1251
#define Matching_unpresented_deposits	1252
#define Memorising_by_percentage_and_dissecting	1253
#define Memorising_by_value_and_dissecting	1254
#define Memorising_by_value_and_percentage_and_dissecting	1255
#define Memorising_on_a_variable_narrative_field_using_wildcards	1256
#define Memorising_on_entry_type_only	1257
#define Memorising_on_narrative	1258
#define Merging_a_payee_list	1259
#define Merging_charts_of_accounts	1261
#define Mouse_conventions	1263
#define MYOB_Accountants_Office_Previously_CA_Systems_GL	1266
#define MYOB_Accounting	1267
#define New_Payee_Name	1268
#define Off_site_BankLink_client	1269
#define Off_site_BankLink_Connect_client	1270
#define Opening_a_client_file	1273
#define Opening_balances	1274
#define Overriding_GST	1277
#define Payees	1278
#define Payments_graph	1279
#define Practice_details	1280
#define Practice_GST_defaults_NZ	1281
#define Print_preview_options	1282
#define Printer_set_up	1283
#define Producing_a_coding_report	1284
#define Producing_the_Business_Activity_Statement	1285
#define Profit_Loss_12_months_actual	1288
#define Profit_Loss_12_Months_actual_or_budget	1289
#define Profit_Loss_Actual	1290
#define Profit_Loss_Actual_and_budget	1291
#define Profit_Loss_Actual_budget_and_variance	1292
#define Profit_Loss_Custom	1293
#define Profit_Loss_reports	1294
#define Purging_entries	1295
#define QuickBooks	1296
#define Recent_enhancements	1297
#define Refresh_chart	1298
#define Report_Groups	1300
#define Reporting_on_tasks	1301
#define Reset_the_status_of_a_client	1302
#define Resetting_a_user	1303
#define Restoring_column_defaults	1304
#define Running_the_Download_Report	1305
#define Sales_graph	1306
#define Save_to_file_options	1307
#define Saving_a_client_file	1308
#define Saving_historical_data	1309
#define Scheduled_Reports	1310
#define Selecting_data_for_coding	1311
#define Selecting_from_multiple_bank_accounts	1312
#define Selecting_the_client_and_date_range	1313
#define Sending_contact_details	1315
#define Sequence_of_memorisation	1316
#define Set_up_GST	1317
#define Setting_Practice_GST_Defaults	1318
#define Setting_up_BankLink_users	1321
#define Setting_up_new_accounts	1322
#define Setting_up_workstations	1324
#define Solution_6_Accounts_Xlon_ATI_for_version_8_onwards_Australia_	1327
#define Solution_6_MAS_Australia_	1328
#define Solution_6_MAS_New_Zealand_	1329
#define Sorting_by_Account_Code	1331
#define Sorting_by_Amount	1332
#define Sorting_by_Analysis_New_Zealand_	1333
#define Sorting_by_Cheque_Number	1334
#define Sorting_by_Coded_By	1335
#define Sorting_by_Date_Effective	1336
#define Sorting_by_Date_Presented_Bank_Statement_Date_	1337
#define Sorting_by_Entry_Type	1338
#define Sorting_by_Narration	1339
#define Sorting_by_Other_Party_New_Zealand_	1340
#define Sorting_by_Particulars_New_Zealand_	1341
#define Sorting_by_Reference	1343
#define Sorting_by_Statement_Details	1344
#define Sorting_entries	1345
#define Spending_by_payee_reports	1346
#define Stage_1_Linking_stock_on_hand_to_opening_and_closing_stock	1347
#define Stage_1_Welcome_to_the_Year_End_Balances_Wizard	1348
#define Stage_2_Adjust_Year_End_Balances	1349
#define Stage_2_Linking_opening_and_closing_stock	1350
#define Stage_3_Adding_opening_balances_for_stock_on_hand	1351
#define Stage_3_Print_Year_End_Reports	1352
#define Stage_4_Alternative_View_Overwrite_Existing_Balances	1353
#define Stage_4_Accounting_for_stock_movement_using_a_BankLink_journal	1354
#define Stage_4_Add_Opening_Balances_for_the_New_Financial_Year	1355
#define Stage_5_Allocate_Current_Years_Earnings	1356
#define Stage_6_Finished	1357
#define Standard_report_options	1358
#define Start_here_	1359
#define Step_1_Client_Details	1360
#define Step_2_Accounting_System	1361
#define Step_3_GST_set_up_Australia_	1362
#define Step_3_GST_set_up_New_Zealand_	1363
#define Step_4_Chart_of_Accounts	1364
#define Step_5_Payees	1365
#define Step_6_Bank_Accounts	1366
#define Step_7_Report_Schedule	1367
#define Stock_Adjustment_Journals	1368
#define Summary_of_the_interface_with_AccPac	1369
#define Summary_of_the_interface_with_CaseWare	1370
#define Summary_of_the_interface_with_Handiledger	1371
#define Summary_of_the_interface_with_MYOB_Accounting	1372
#define Summary_of_the_interface_with_MYOB_AO_Australia_	1373
#define Summary_of_the_interface_with_PA_Australia_	1375
#define Summary_of_the_interface_with_PA_New_Zealand_	1376
#define Summary_of_the_interface_with_Solution_6_Accounts	1377
#define Summary_of_the_interface_with_Solution_6_MAS_Australia_	1378
#define Summary_of_the_interface_with_Tax_Assistant	1380
#define Synchronising_client_files	1382
#define System_Options	1383
#define System_Options_Advanced_tab	1384
#define System_Options_General_tab	1386
#define System_Options_Interfaces_tab	1387
#define System_Reports	1390
#define System_requirements	1391
#define Tax_Assistant	1392
#define Template_files	1393
#define The_BankLink_Menu_Bar	1394
#define The_Client_Manager	1400
#define The_download_process	1401
#define The_Guide	1402
#define The_help_viewer	1403
#define The_transaction_data_columns	1405
#define Trading_results_graph	1411
#define Transaction_with_notes	1413
#define Transactions_in_BankLink_after_a_BNotes_import	1414
#define Transferring_transactions_from_BankLink_to_AccPac	1415
#define Transferring_transactions_from_BankLink_to_Attaché_BP	1416
#define Transferring_transactions_from_BankLink_to_BGL_Simple_Fund	1417
#define Transferring_transactions_from_BankLink_to_CaseWare	1418
#define Transferring_transactions_from_BankLink_to_CashManager	1419
#define Transferring_transactions_from_BankLink_to_Comparto	1420
#define Transferring_transactions_from_BankLink_to_Concept_2000	1421
#define Transferring_transactions_from_BankLink_to_HandiLedger	1422
#define Transferring_transactions_from_BankLink_to_Intech	1423
#define Transferring_transactions_from_BankLink_to_M_GL	1424
#define Transferring_transactions_from_BankLink_to_MYOB_Accounting	1425
#define Transferring_transactions_from_BankLink_to_MYOB_AO_Australia_	1426
#define Transferring_transactions_from_BankLink_to_PA_Australia_	1428
#define Transferring_transactions_from_BankLink_to_PA_New_Zealand_	1429
#define Transferring_transactions_from_BankLink_to_QuickBooks	1430
#define Transferring_transactions_from_BankLink_to_Solution_6_Australia_	1431
#define Transferring_transactions_from_BankLink_to_Solution_6_New_Zealand_	1432
#define Transferring_transactions_from_BankLink_to_Solution_6_Accounts	1433
#define Transferring_transactions_from_BankLink_to_Tax_Assistant	1434
#define Trial_balance_report	1436
#define Un_matching_unpresented_cheques	1437
#define Un_matching_unpresented_deposits	1438
#define Unpresented_cheques	1439
#define Unpresented_deposits	1440
#define Unpresented_items	1441
#define Unpresented_transactions	1442
#define Updating_a_client_file_with_new_transactions	1443
#define User_security	1444
#define Using_the_Code_Entries_Screen	1446
#define Viewing_and_editing_master_memorisations	1448
#define Viewing_editing_and_deleting_memorisations	1449
#define What_data_does_BankLink_report_on_	1451
#define What_happens_if_you_do_not_assign_report_groups_	1452
#define What_is_in_the_Guide_	1453
#define Year_end_adjustment_journals	1458
#define Interfacing_with_Acclipse_WebXOffice	1459
#define Exporting_transactions_from_BankLink_to_Acclipse_WebXOffice	1460
#define Importing_transactions_from_Acclipse_WebXOffice_to_BankLink	1461
#define Summary_of_the_interface_with_Solution_6_Superfund	1500
#define Summary_of_the_interface_with_Supercorp_Supervisor_II	1501
#define Transferring_transactions_from_BankLink_to_Solution_6_Superfund	1502
#define Transferring_transactions_from_BankLink_to_Supercorp_Supervisor_II	1503
#define Copying_a_chart_from_Solution_6_Superfund_into_BankLink	1504
#define Copying_a_chart_from_Supercorp_Supervisor_II_into_BankLink	1505
#define Accessing_a_Client_Authority_Form	1506
#define Accessing_a_Third_Party_Authority_form	1507
#define Adding_and_importing_Prospects	1508
#define Adding_initial_unpresented_withdrawals	1509
#define Adding_manual_bank_accounts	1510
#define Adding_manual_data	1511
#define Adding_unpresented_withdrawals	1512
#define Business_Products_Interface_OFX_QIF_files	1513
#define Cancelling_unpresented_withdrawals	1514
#define CatSoft_LedgerCat	1515
#define Copying_a_Chart_from_CatSoft_LedgerCat	1516
#define Combining_bank_accounts	1517
#define Deleting_and_editing_manual_data	1518
#define Exporting_charges_to_APS_Advance	1519
#define Exporting_charges_to_MYOB_Viztopia	1520
#define Exporting_charges_to_other_practice_management_systems	1521
#define Generate_Scheduled_Reports_Message_Setup	1522
#define Interfacing_with_Solution_6_Superfund	1523
#define Interfacing_with_Supercorp_Supervisor_II	1524
#define Merging_and_printing_documents_using_Client_Manager	1526
#define Merging_and_sending_e_mails_using_Client_Manager	1527
#define Praemium	1528
#define Producing_QIF_files	1529
#define Producing_OFX_Files_Versions_1_2_	1530
#define Saving_manual_data	1531
#define Sending_reports_from_BankLink_to_Acclipse_WebPractice	1532
#define Setting_up_the_link_to_Praemium	1533
#define Statements_and_Download_Documents	1534
#define Summary_of_the_interface_with_CatSoft_LedgerCat	1535
#define System_Options_Links_tab	1536
#define Transferring_transactions_from_BankLink_to_CatSoft_LedgerCat	1537
#define Transferring_transactions_from_BankLink_to_Praemium	1538
#define Transferring_transactions_from_BankLink_to_XPA_Version_8	1539
#define Unpresented_withdrawals	1541
#define Creating_documents_and_e_mails_using_Client_Manager	1544
#define Bank_Accounts1	1545
#define Choosing_files_to_display_in_the_Clients_page	1601
#define Client_Details	1602
#define Client_Files	1603
#define Client_Tasks	1604
#define Clients_page_Client_Details	1605
#define Combining_manual_bank_accounts	1606
#define Configuring_columns_for_dissections	1607
#define Configuring_Columns_for_historical_and_manual_data_entry	1608
#define Configuring_columns_in_the_Client_Manager	1609
#define Configuring_the_Enter_Journal_window	1610
#define Contact_Clients	1611
#define Copying_a_chart_from_MYOB_Accountants_Enterprise_MAS_into_BankLink	1612
#define Copying_a_chart_from_MYOB_AO_into_BankLink	1613
#define Copying_a_chart_from_MYOB_AO_into_BankLink_NZ	1615
#define Copying_a_chart_from_XPA_Version_8_into_BankLink	1617
#define Exporting_charges_to_HandiSoft_Time_and_Billing	1618
#define Exporting_charges_to_MYOB_Accountants_Office	1619
#define How_BankLink_populates_the_Fuel_Tax_Worksheet	1621
#define Interface_to_APS_Tax	1622
#define Interface_to_MYOB_Accountants_Office_Tax	1623
#define Interface_to_Tax_Elite	1624
#define Interfacing_with_MYOB_Accountants_Enterprise_MAS	1625
#define Removing_read_only_copies_of_files_from_your_client_s_BankLink_Books_system	1626
#define Summary_of_the_interface_with_MYOB_Accountants_Office	1627
#define System_Options_Updates	1628
#define The_Client_Home_Page	1629
#define Xcede_Professional_Accounting_Version_8	1631
#define Favourite_Reports	1632
#define Adding_reports_to_the_Favourite_reports_list	1633
#define Generating_reports_from_the_Favourite_Reports_list	1634
#define Renaming_Favourite_Reports	1635
#define Deleting_Favourite_Reports	1636
#define GST_adjustments_calculation_sheet_IR372	1637
#define Desktop_Super	1638
#define BGL_Simple_Ledger	1639
#define Transferring_transactions_from_BankLink_Practice_to_BGL_Simple_Ledger	1641
#define Working_with_Notes	1404
#define Report_and_Graph_Options	2000
#define Report_and_Graph_Options_Coding	2001
#define Report_and_Graph_Options_Financial	2002
#define Report_and_Graph_Options_Graphs	2003
#define Report_and_Graph_Options_GST	2004
#define Report_and_Graph_Options_Ledger	2005
#define Report_and_Graph_Options_Listings	2006
#define Report_and_Graph_Options_Other	2007
#define Adding_new_jobs	2008
#define Completing_jobs	2009
#define Editing_jobs	2010
#define Jobs	2011
#define Reopening_jobs	2012
#define Groups	2013
#define Client_Types	2014
#define Archiving_client_files	2015
#define Setting_up_graph_titles_and_headings	2016
#define Coding_by_Job_report	2017
#define List_jobs	2018
#define List_Groups	2019
#define Client_Status_Report	1097
#define Backing_up_and_restoring_BankLink_Books_files	1271
#define Coding_transactions_for_BGL_Simple_Fund	2020
#define Coding_transactions_for_MYOB_Superfund	2022
#define Coding_transactions_for_Supercorp_SuperVisor_II	2023
#define 12_months_budget	2025
#define Assigning_job_codes_in_a_dissection	2026
#define Charges	2027
#define Configuring_the_Journal_Entries_Screen	2028
#define Edit_All_Columns_in_the_Enter_Journal_window	2029
#define IRESS_Xplan	2030
#define Journal_entry_toolbar_buttons	2031
#define Journals_and_notes	2032
#define List_Charges	2033
#define Setting_up_the_link_to_IRESS_Xplan	2034
#define Using_the_Enter_Journal_window	2035
#define Using_the_Journal_Entries_Screen	2036
#define Viewing_the_list_of_financial_institutions	2037
#define Memorising_on_value	2038
#define Saving_and_loading_custom_Coding_Report_templates	2039
#define Setting_up_a_custom_Coding_Report	2040
#define Using_the_budget_functions	2041
#define Importing_historical_data	2042
#define Importing_contact_details	2043
#define Coding_VAT	2050
#define Report_and_Graph_Options_VAT	2051
#define VAT_journals	2052
#define Finalise_accounting_period_for_VAT_purposes	2053
#define VAT_summary	2054
#define VAT_audit_trail	2055
#define VAT_overrides	2056
#define VAT_Reports	2057
#define VAT_return	2058
#define List_VAT_details	2059
#define List_foreign_currency_entries	2060
#define Setting_Practice_VAT_defaults	2061
#define Assigning_VAT_classes_to_the_chart_of_accounts	2062
#define Practice_VAT_defaults	2063
#define Coding_Optimisation_Report	2064
#define Converting_a_chart_of_accounts	2065
#define Find_and_replace_a_chart_of_accounts_code	2066
#define Adding_and_editing_your_practice_email_signature	2067
#define Custom_Documents	2068
#define Interfacing_with_superMate	2070
#define Interfacing_with_ProSuper	2071
#define Interfacing_with_RewardSuper	2072
#define Coding_transactions_for_superMate	2073
#define Coding_transactions_for_Desktop_Super	2074
#define Transferring_transactions_from_BankLink_Practice_to_ProSuper	2075
#define Transferring_transactions_from_BankLink_Practice_to_IRESS_Xplan	2076
#define Transferring_transactions_from_BankLink_Practice_to_Ledger_Elite	2077
#define Transferring_transactions_from_BankLink_Practice_to_RewardSuper	2078
#define Transferring_transactions_from_BankLink_Practice_to_superMate	2079
#define Copying_a_chart_from_ProSuper_into_BankLink_Practice	2080
#define Copying_a_chart_from_superMate_into_BankLink_Practice	2081
#define Summary_of_the_interface_with_superMate	2082
#define Summary_of_the_interface_with_XPA_Version_8	2083
#define Summary_of_the_interface_with_MYOB_Accounting_General_Journals_	2084
#define Setting_up_the_link_to_RewardSuper	2086
#define Copying_a_chart_from_BGL_Simple_Ledger_into_BankLink_Practice	2087
#define Copying_a_chart_from_Desktop_Super_into_BankLink_Practice	2088
#define Copying_a_chart_from_Ledger_Elite_into_BankLink_Practice	2089
#define Summary_of_the_interface_with_Accomplish_Cash_Manager	2090
#define Summary_of_the_interface_with_Attache_Business_Partner	2091
#define Summary_of_the_interface_with_BGL_Simple_Fund	2092
#define Summary_of_the_interface_with_BGL_Simple_Ledger	2093
#define Summary_of_the_interface_with_Comparto	2094
#define Summary_of_the_interface_with_Concept_2000	2095
#define Summary_of_the_interface_with_Desktop_Super	2096
#define Summary_of_the_interface_with_Intech	2097
#define Summary_of_the_interface_with_Ledger_Assistant	2098
#define Summary_of_the_interface_with_Ledger_Elite	2099
#define Summary_of_the_interface_with_M_GL	2100
#define Summary_of_the_interface_with_MYOB_AO	2103
#define Summary_of_the_interface_with_QuickBooks	2101
#define Copying_a_chart_from_MYOB_Accounting_into_BankLink_Practice	2102
#define Transferring_transactions_from_BankLink_to_Desktop_Super	2105
#define Transferring_transactions_from_BankLink_Practice_to_MYOB_Accounting	2106
#define Sending_a_frequency_change_request_from_BankLink_Practice	2107
#define Data_frequency	2108
#define Interfacing_with_Sage_Handisoft_Superfund	2109
#define Setting_up_the_link_to_Sage_Handisoft_Superfund	2110
#define Transferring_transactions_to_Sage_Handisoft_Superfund	2111
#define Differences_between_data_frequencies	2112
#define Creating_a_BankLink_Notes_Online_file_for_a_client_to_access	2113
#define Importing_a_BankLink_Notes_Online_file_into_BankLink_Practice	2114
#define Interfacing_with_Class_Super	2069
#define Copying_a_chart_from_Class_Super_into_BankLink_Practice	2115
#define GST_Return_Transitional	2116
#define Copying_a_chart_from_Sage_50_Accounts_into_BankLink_Practice	2117
#define Sage_50_Accounts	2118
#define TASBooks	2119
#define Copying_a_chart_from_TASBooks_into_BankLink_Practice	2120
#define Maintain_Currencies	2121
#define Maintain_Exchange_Rates	2122
#define Importing_a_CSV_format_chart_into_BankLink_Practice	2124
#define Copying_a_chart_from_QuickBooks_Pro_into_BankLink_Practice	2125
#define QuickBooks_Pro	2126
#define List_Provisional_Accounts	2132
#define What_s_New_in_BankLink_Practice_2011_	2133
#define Chapter_7_Historical_and_manual_data_entry	1074
#define Adding_provisional_data	2131
#define Importing_provisional_data	2127
#define Signing_clients_onto_The_BankLink_Service	1326
#define Combining_manual_and_system_bank_accounts	1543
#define Adding_manual_bank_accounts_uk	2123
#define Merging	1260
#define Filtering_files_in_the_Clients_page	1620
#define The_Processing_Status_column	1630
#define Copying_a_help_topic	1406
#define Printing_a_help_topic	1409
#define Setting_up_report_schedules	1323
#define Assigning_client_files_to_users	1020
#define To_get_help_in_a_BankLink_window	1408
#define Finding_a_help_topic	1407
#define Using_the_Guide	1447
#define Editing_manual_bank_accounts_details	1542
#define The_basics	1399
#define The_status_bar	1395
#define Matching_unpresented_withdrawals	1525
#define Un_matching_unpresented_withdrawals	1540
#define Assigning_GST_classes_to_chart_of_account_codes	1023
#define Ledger_Report	1235
#define Total_bank_balance_graph	1410
#define One_page_summary	1272
#define Copying_a_chart_from_PA_7_into_BankLink	1132
#define Transferring_transactions_from_BankLink_to_PA_7	1435
#define Professional_Accounting_7	1457
#define Audit_Report	2134
#define Sending_a_client_file_via_BankLink_Online	2135
#define Updating_a_client_file_from_BankLink_Online	2136
#define Sending_a_client_file_to_file	1089
#define Updating_a_client_file_from_a_folder	1088
#define Sending_a_client_file_via_email	1314
#define Transferring_transactions_from_BankLink_Practice_to_QuickBooks_Pro	2137
