unit LicenseDlg;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls,
  bkXPThemes,
  OsFont, ExtCtrls, ComCtrls,
  bkProduct;

type
  TDlgLicense = class(TForm)
    mmoEULA: TMemo;
    lRead: TLabel;
    lAccept: TLabel;
    pBtn: TPanel;
    btnNo: TButton;
    btnYes: TButton;
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
    FAbout: Boolean;
    procedure SetAbout(Value: Boolean);
    procedure DoRebranding();
    procedure UseAUEula;
    procedure UseNZEula;
  public
    { Public declarations }
    property About: Boolean read FAbout write SetAbout;
  end;

implementation
{$R *.dfm}

uses
  bkConst, Globals,
  IniFiles,
  CountryUtils;

procedure TDlgLicense.DoRebranding;
begin
  lAccept.Caption := 'Do you accept all the terms of the preceding Licence Agreement? ' +
                     'If you choose No, you will not be able to login. To use ' +
                     BRAND_FULL_PRACTICE + ' you must accept this agreement.';
end;

procedure TDlgLicense.FormCreate(Sender: TObject);
begin
  bkXPThemes.ThemeForm( Self);
  FAbout := False;
  mmoEULA.WordWrap := True;

  DoRebranding();

  case GetCountry of
    whAustralia : UseAUEula;
    whNewZealand: UseNZEula;
  end;
end;

procedure TDlgLicense.UseAUEula;
var
  AUEula: TStringList;
begin
  mmoEula.Clear;
  try
    AUEula := TStringList.Create;
    AUEula.Clear;
    AUEula.Add('Australian EULA');
    AUEula.Add('');
    AUEula.Add('Last updated: 14 January 2014');
    AUEula.Add('');
    AUEula.Add('Software End-User Licence Agreement for Media Transfer Services Limited');
    AUEula.Add('(‘MYOB BankLink’). ');
    AUEula.Add('');
    AUEula.Add('IMPORTANT NOTICE PLEASE READ CAREFULLY BEFORE INSTALLING OR USING');
    AUEula.Add('THE SOFTWARE:');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('1	Agreement');
    AUEula.Add('');
    AUEula.Add('1.1	This Software End-User Licence Agreement (''Agreement'') is between');
    AUEula.Add('	you and MYOB BankLink.');
    AUEula.Add('');
    AUEula.Add('1.2	This computer software, together with any supporting documentation');
    AUEula.Add('        	and any modifications or amendments made by MYOB BankLink');
    AUEula.Add('        	(‘the Software’), is owned by MYOB BankLink.');
    AUEula.Add('        	Provided your copy of the Software has been lawfully obtained, and');
    AUEula.Add('        	in relation to InvoicePlus and PayablesPlus, provided you are a');
    AUEula.Add('        	registered user of MYOB BankLink''s services, you are authorised to use');
    AUEula.Add('        	the Software in accordance with this Agreement.');
    AUEula.Add('');
    AUEula.Add('1.3	By proceeding to install, store, load, execute and display');
    AUEula.Add('        	(individually or collectively, ‘Use’) the Software, you agree to');
    AUEula.Add('        	be bound by the terms of this Agreement. If your copy of the');
    AUEula.Add('        	Software has not been legally obtained or you do not agree to the');
    AUEula.Add('        	terms of this Agreement, MYOB BankLink is not willing to licence the');
    AUEula.Add('        	Software to you and you must not Use the Software.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('2	Grant of licence');
    AUEula.Add('');
    AUEula.Add('2.1	In consideration of you agreeing to abide by the terms of this');
    AUEula.Add('        	Agreement MYOB BankLink hereby grants you a non-exclusive,');
    AUEula.Add('        	non-transferable licence to Use the Software in accordance with');
    AUEula.Add('        	this Agreement.');
    AUEula.Add('');
    AUEula.Add('2.2	The licence is perpetual unless terminated in accordance with');
    AUEula.Add('        	clause 7.');
    AUEula.Add('');
    AUEula.Add('2.3	With regard to the InvoicePlus and PayablesPlus products, you may');
    AUEula.Add('        	Use one copy of the Software on a single computer.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('3	Limitations on Use');
    AUEula.Add('');
    AUEula.Add('3.1	The Software licence is personal to you; you cannot sell,');
    AUEula.Add('        	sub-licence, assign, transfer, charge, lend the Software to any');
    AUEula.Add('        	other person or entity or otherwise dispose of the rights or');
    AUEula.Add('        	obligations under this Agreement without the written consent of');
    AUEula.Add('        	MYOB BankLink.');
    AUEula.Add('');
    AUEula.Add('3.2	You cannot copy, alter, modify or reproduce the Software, but you');
    AUEula.Add('        	may make one copy of the Software for backup purposes only.');
    AUEula.Add('        	Except as otherwise permitted at law, you cannot reverse assemble');
    AUEula.Add('        	or reverse compile or directly or indirectly allow or cause a');
    AUEula.Add('        	third party to reverse assemble or reverse compile the whole or');
    AUEula.Add('        	any part of the Software.');
    AUEula.Add(' ');
    AUEula.Add('3.3	MYOB BankLink may sell, sub-licence, assign, transfer, charge or lend');
    AUEula.Add('        	the Software to any other person or entity or otherwise dispose of');
    AUEula.Add('        	the rights or obligations under this Agreement at any time without');
    AUEula.Add('        	your consent.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('4	Title');
    AUEula.Add('');
    AUEula.Add('4.1	All title and intellectual property rights in the Software remain');
    AUEula.Add('        	with MYOB BankLink (or its Licensors). You acknowledge that rights in');
    AUEula.Add('        	the Software are licensed (not sold) to you, and that you have no');
    AUEula.Add('        	rights in, or to, the Software other than the right to Use the');
    AUEula.Add('        	Software in accordance with the terms of this Agreement. You');
    AUEula.Add('        	acknowledge that you have no right to have access to the Software');
    AUEula.Add('        	in source code form or in unlocked coding or with comments.');
    AUEula.Add('');
    AUEula.Add('4.2	You will notify MYOB BankLink as soon as you become aware of any');
    AUEula.Add('        	infringement, suspected infringement or alleged infringement of');
    AUEula.Add('        	MYOB BankLink’s intellectual property rights in the Software.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('5	Warranties');
    AUEula.Add('');
    AUEula.Add('5.1	Except as otherwise agreed, MYOB BankLink is not obliged to support');
    AUEula.Add('        	the Software, whether by providing advice, training, error-correction,');
    AUEula.Add('        	modification, new releases or enhancements or otherwise.');
    AUEula.Add('');
    AUEula.Add('5.2	If you acquired this Software in New Zealand, to the extent');
    AUEula.Add('        	permitted by law, MYOB BankLink excludes and disclaims all and any');
    AUEula.Add('        	guarantees and/or warranties whether express, implied, statutory');
    AUEula.Add('        	or otherwise in respect of the Software and in particular, to the');
    AUEula.Add('        	extent that they are applicable, expressly excludes the provisions');
    AUEula.Add('        	of the New Zealand Consumer Guarantees Act 1993 pursuant to clause');
    AUEula.Add('        	43(2) thereof and the provisions of the New Zealand Sale of Goods');
    AUEula.Add('        	Act 1908 pursuant to clause 56 thereof. You confirm that you have');
    AUEula.Add('        	acquired the Software for business purposes.');
    AUEula.Add('');
    AUEula.Add('5.3	If you acquired this Software in Australia:');
    AUEula.Add('(a)	this Agreement does not exclude, restrict or modify:');
    AUEula.Add('	(i)	the application of any provision of the Australian Consumer Law');
    AUEula.Add('		(‘ACL’) (whether applied as a law of the Commonwealth or any');
    AUEula.Add('		State or Territory of Australia);');
    AUEula.Add('	(ii)	the exercise of any right or remedy conferred by the ACL; or');
    AUEula.Add('	(iii)	the liability of MYOB BankLink for a failure to comply with any');
    AUEula.Add('		applicable consumer guarantees, where to do so would:');
    AUEula.Add('		A.	contravene the ACL; or');
    AUEula.Add('		B.	cause any part of this Agreement to be void.  ');
    AUEula.Add('(b)	to the extent permitted by law, MYOB BankLink excludes and disclaims all');
    AUEula.Add('	and any guarantees and/or warranties whether express, implied, statutory');
    AUEula.Add('	or otherwise in respect of the Software, except for any condition,');
    AUEula.Add('	warranty, guarantee, right or remedy under the ACL. Nothing in this clause 5');
    AUEula.Add('	excludes, restricts or modifies any condition, warranty, guarantee, right or');
    AUEula.Add('	remedy under the ACL.');
    AUEula.Add('');
    AUEula.Add('5.4	You acknowledge that MYOB BankLink does not warrant or promise that the');
    AUEula.Add('        	Software will meet your requirements and that you have solely exercised');
    AUEula.Add('        	and relied upon your own skill and judgment in determining whether the');
    AUEula.Add('        	Software meets your particular requirements, and have not relied on any');
    AUEula.Add('        	statement or representation by or on behalf of MYOB BankLink (unless');
    AUEula.Add('        	made fraudulently).');
    AUEula.Add('');
    AUEula.Add('5.5	MYOB BankLink is providing this Software to you "AS IS" and you');
    AUEula.Add('        	acknowledge that risk of loss or of damage to your computer system');
    AUEula.Add('        	or data at all times remains with you.');
    AUEula.Add(' ');
    AUEula.Add('5.6	MYOB BankLink does not warrant that:');
    AUEula.Add('');
    AUEula.Add('        	5.6.1	Any of the data provided by or on behalf of MYOB BankLink');
    AUEula.Add('		and received by you for use with the Software will be accurate');
    AUEula.Add('		or virus free;');
    AUEula.Add('');
    AUEula.Add('        	5.6.2	The Software will operate without interruption or errors; or');
    AUEula.Add('');
    AUEula.Add('        	5.6.3	That the Software will not affect the operation of other');
    AUEula.Add('		installed applications.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('6	Liability');
    AUEula.Add('');
    AUEula.Add('6.1	MYOB BankLink will not be liable to you for any loss or damage');
    AUEula.Add('        	(including, without limitation, consequential loss or damage)');
    AUEula.Add('        	suffered by you whether arising directly or indirectly from the');
    AUEula.Add('        	Use of the Software or any data provided by or on behalf of');
    AUEula.Add('        	MYOB BankLink under this Agreement or from any failure or omission');
    AUEula.Add('        	on the part of MYOB BankLink or otherwise.');
    AUEula.Add(' ');
    AUEula.Add('6.2	In no event will MYOB BankLink be liable for any remote, indirect,');
    AUEula.Add('        	consequential, punitive, special or incidental damages, including');
    AUEula.Add('        	without limitation, damages resulting from loss of any data, loss');
    AUEula.Add('        	of income or profits or business interruption, or cost of cover');
    AUEula.Add('        	whether based in contract, tort (including negligence), at law, in');
    AUEula.Add('        	equity, under statute or otherwise. This limitation will apply even if');
    AUEula.Add('        	MYOB BankLink has been advised of the possibility of such damages.');
    AUEula.Add('');
    AUEula.Add('6.3	Where the ACL applies (if you acquired this Software in Australia), then');
    AUEula.Add('        	the liability of MYOB BankLink for any loss arising as a result of or in ');
    AUEula.Add('        	relation to the supply by MYOB BankLink of the Software, including any');
    AUEula.Add('        	economic or consequential loss which may be sustained or incurred, shall');
    AUEula.Add('        	be limited to:');
    AUEula.Add('');
    AUEula.Add('        	6.3.1	The replacement of the Software or the supply of');
    AUEula.Add('                	equivalent Software;');
    AUEula.Add('');
    AUEula.Add('        	6.3.2	The repair of the Software;');
    AUEula.Add('');
    AUEula.Add('        	6.3.3	The payment of the cost of repairing or replacing the');
    AUEula.Add('                	Software or acquiring equivalent Software;');
    AUEula.Add('');
    AUEula.Add('        	6.3.4	The payment of the cost of having the Software replaced;');
    AUEula.Add('');
    AUEula.Add('        	6.3.5	The payment for the reduction in value of the Software; or');
    AUEula.Add('');
    AUEula.Add('        	6.3.6	The cost of the refund of the Software license fee, if');
    AUEula.Add('                	any, paid by you. However, nothing in this clause 6');
    AUEula.Add('                	excludes, restricts or modifies any condition, warranty,');
    AUEula.Add('                	guarantee, right or remedy under the ACL.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('7	Termination');
    AUEula.Add('');
    AUEula.Add('7.1	Without prejudice to any other rights, MYOB BankLink may terminate');
    AUEula.Add('        	this Agreement by written notice to you with immediate effect if you');
    AUEula.Add('        	fail to comply with the terms and conditions of this Agreement or');
    AUEula.Add('        	if you become bankrupt or insolvent (or suffer any similar');
    AUEula.Add('        	circumstances anywhere in the world).');
    AUEula.Add('');
    AUEula.Add('7.2	Upon termination for any reason:');
    AUEula.Add('');
    AUEula.Add('        	7.2.1	All rights granted to you under this Agreement shall');
    AUEula.Add('                	cease;');
    AUEula.Add('');
    AUEula.Add('        	7.2.2	You must cease all Use of the Software and any other');
    AUEula.Add('                	activities authorised by this Agreement; and');
    AUEula.Add('');
    AUEula.Add('        	7.2.3	You must immediately uninstall the Software and destroy');
    AUEula.Add('                	all copies of the Software in your possession and all its');
    AUEula.Add('                	component parts.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('8	Miscellaneous');
    AUEula.Add('');
    AUEula.Add('Entire Agreement');
    AUEula.Add('');
    AUEula.Add('8.1	This Agreement contains everything the parties have agreed in');
    AUEula.Add('        	relation to the subject matter it deals with. No party can rely on');
    AUEula.Add('        	an earlier written document or anything said or done by or on');
    AUEula.Add('        	behalf of another party before this agreement was executed.');
    AUEula.Add(' ');
    AUEula.Add('Variation');
    AUEula.Add('');
    AUEula.Add('8.2	No variation of this agreement will be of any force or effect');
    AUEula.Add('        	unless it is in writing and signed by each party to this');
    AUEula.Add('        	agreement.');
    AUEula.Add('');
    AUEula.Add('Privity of contract');
    AUEula.Add('');
    AUEula.Add('8.3	A party who is not you or MYOB BankLink shall have no right to enforce');
    AUEula.Add('        	any term under this Agreement whether under the Contracts (Privity) Act');
    AUEula.Add('        	1982 (if you acquired this Software in New Zealand) or any other local');
    AUEula.Add('        	Act or provision. This clause does not affect any right or remedy of');
    AUEula.Add('        	any person which exists, or is available, other than pursuant to the');
    AUEula.Add('        	relevant Act.');
    AUEula.Add('');
    AUEula.Add('Governing law');
    AUEula.Add('');
    AUEula.Add('8.4	If you acquired this Software in Australia, this Agreement and any');
    AUEula.Add('        	dispute or non-contractual obligation arising out of or in');
    AUEula.Add('        	connection with it shall be governed by and construed in');
    AUEula.Add('        	accordance with the laws of Victoria, and each party hereby');
    AUEula.Add('        	submits to the exclusive jurisdiction of the courts of Victoria over any');
    AUEula.Add('        	dispute arising out of or in connection with this Agreement.');
    AUEula.Add('');
    AUEula.Add('8.5	If you acquired this Software in New Zealand, this Agreement and');
    AUEula.Add('        	any dispute or non-contractual obligation arising out of or in');
    AUEula.Add('        	connection with it shall be governed by and construed in');
    AUEula.Add('        	accordance with the laws of New Zealand, and each party hereby');
    AUEula.Add('        	submits to the exclusive jurisdiction of the courts of New Zealand');
    AUEula.Add('        	over any dispute arising out of or in connection with this');
    AUEula.Add('        	Agreement.');
    AUEula.Add('');
    AUEula.Add('');
    AUEula.Add('9	Collection of Usage Information');
    AUEula.Add('');
    AUEula.Add('        	You agree that MYOB BankLink shall have the right to use, copy, store,');
    AUEula.Add('        	transfer, transmit, display and analyse any electronic data, information');
    AUEula.Add('        	or material, including the menus you select, the number of times each');
    AUEula.Add('        	is selected and the number of client files involved, which is sourced');
    AUEula.Add('        	by or through Use of the Software.');
    AUEula.Add('');
    AUEula.Add('        	You also agree that MYOB BankLink may collect, store, use and disclose');
    AUEula.Add('        	personal data (including personal data/information of you/your');
    AUEula.Add('        	clients) provided by you to MYOB BankLink (including, without');
    AUEula.Add('        	limitation your/your client''s name and user code). MYOB BankLink will');
    AUEula.Add('        	protect the information collected against unauthorised access, use');
    AUEula.Add('        	and disclosure and shall handle the same only in accordance with');
    AUEula.Add('        	MYOB BankLink''s privacy policy and by use of the Software you consent');
    AUEula.Add('        	to the collection, storage, use and disclosure of personal');
    AUEula.Add('        	information as set out in the relevant Privacy Policy. MYOB BankLink''s');
    AUEula.Add('        	privacy policy for New Zealand can be viewed at');
    AUEula.Add('        	http://www.banklink.co.nz/index.php/privacy, or for Australia at');
    AUEula.Add('        	http://www.banklink.com.au/index.php/privacy');
    AUEula.Add('');
    AUEula.Add('        	You warrant that you will not provide any personal information of');
    AUEula.Add('        	your clients to MYOB BankLink unless you:');
    AUEula.Add('        	(a)	have the prior consent of those clients to the disclosure;');
    AUEula.Add('                	and');
    AUEula.Add('        	(b)	have provided the clients with a copy of the relevant');
    AUEula.Add('                	MYOB BankLink Privacy Policy and that they have accepted and');
    AUEula.Add('                	consented to the collection, storage, use and disclosure');
    AUEula.Add('                	of personal information as set out in the relevant');
    AUEula.Add('                	Privacy Policy.');
    AUEula.Add('');
    AUEula.Add('        	You acknowledge, agree and further warrant that you will collect,');
    AUEula.Add('        	store, use and disclose the personal information of any individual');
    AUEula.Add('        	that may be provided to you by MYOB BankLink in accordance with the');
    AUEula.Add('        	MYOB BankLink Privacy Policy that is relevant to your jurisdiction.');

    mmoEULA.Lines := AUEula;
  finally
    FreeAndNil(AUEula);
  end;
end;

procedure TDlgLicense.UseNZEula;
var
  NZEula: TStringList;
begin
  mmoEula.Clear;
  try
    NZEula := TStringList.Create;
    NZEula.Add('New Zealand EULA');
    NZEula.Add('');
    NZEula.Add('Last updated: 14 January 2014');
    NZEula.Add('');
    NZEula.Add('Software End-User Licence Agreement for Media Transfer Services Limited');
    NZEula.Add('(‘MYOB BankLink’). ');
    NZEula.Add('');
    NZEula.Add('IMPORTANT NOTICE PLEASE READ CAREFULLY BEFORE INSTALLING OR USING');
    NZEula.Add('THE SOFTWARE:');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('1	Agreement');
    NZEula.Add('');
    NZEula.Add('1.1	This Software End-User Licence Agreement (''Agreement'') is between');
    NZEula.Add('	you and MYOB BankLink.');
    NZEula.Add('');
    NZEula.Add('1.2	This computer software, together with any supporting documentation');
    NZEula.Add('        	and any modifications or amendments made by MYOB BankLink');
    NZEula.Add('        	(‘the Software’), is owned by MYOB BankLink.');
    NZEula.Add('        	Provided your copy of the Software has been lawfully obtained, and');
    NZEula.Add('        	in relation to InvoicePlus and PayablesPlus, provided you are a');
    NZEula.Add('        	registered user of MYOB BankLink''s services, you are authorised to use');
    NZEula.Add('        	the Software in accordance with this Agreement.');
    NZEula.Add('');
    NZEula.Add('1.3	By proceeding to install, store, load, execute and display');
    NZEula.Add('        	(individually or collectively, ‘Use’) the Software, you agree to');
    NZEula.Add('        	be bound by the terms of this Agreement. If your copy of the');
    NZEula.Add('        	Software has not been legally obtained or you do not agree to the');
    NZEula.Add('        	terms of this Agreement, MYOB BankLink is not willing to licence the');
    NZEula.Add('        	Software to you and you must not Use the Software.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('2	Grant of licence');
    NZEula.Add('');
    NZEula.Add('2.1	In consideration of you agreeing to abide by the terms of this');
    NZEula.Add('        	Agreement MYOB BankLink hereby grants you a non-exclusive,');
    NZEula.Add('        	non-transferable licence to Use the Software in accordance with');
    NZEula.Add('        	this Agreement.');
    NZEula.Add('');
    NZEula.Add('2.2	The licence is perpetual unless terminated in accordance with');
    NZEula.Add('        	clause 7.');
    NZEula.Add('');
    NZEula.Add('2.3	With regard to the InvoicePlus and PayablesPlus products, you may');
    NZEula.Add('        	Use one copy of the Software on a single computer.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('3	Limitations on Use');
    NZEula.Add('');
    NZEula.Add('3.1	The Software licence is personal to you; you cannot sell,');
    NZEula.Add('        	sub-licence, assign, transfer, charge, lend the Software to any');
    NZEula.Add('        	other person or entity or otherwise dispose of the rights or');
    NZEula.Add('        	obligations under this Agreement without the written consent of');
    NZEula.Add('        	MYOB BankLink.');
    NZEula.Add('');
    NZEula.Add('3.2	You cannot copy, alter, modify or reproduce the Software, but you');
    NZEula.Add('        	may make one copy of the Software for backup purposes only.');
    NZEula.Add('        	Except as otherwise permitted at law, you cannot reverse assemble');
    NZEula.Add('        	or reverse compile or directly or indirectly allow or cause a');
    NZEula.Add('        	third party to reverse assemble or reverse compile the whole or');
    NZEula.Add('        	any part of the Software.');
    NZEula.Add(' ');
    NZEula.Add('3.3	MYOB BankLink may sell, sub-licence, assign, transfer, charge or lend');
    NZEula.Add('        	the Software to any other person or entity or otherwise dispose of');
    NZEula.Add('        	the rights or obligations under this Agreement at any time without');
    NZEula.Add('        	your consent.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('4	Title');
    NZEula.Add('');
    NZEula.Add('4.1	All title and intellectual property rights in the Software remain');
    NZEula.Add('        	with MYOB BankLink (or its Licensors). You acknowledge that rights in');
    NZEula.Add('        	the Software are licensed (not sold) to you, and that you have no');
    NZEula.Add('        	rights in, or to, the Software other than the right to Use the');
    NZEula.Add('        	Software in accordance with the terms of this Agreement. You');
    NZEula.Add('        	acknowledge that you have no right to have access to the Software');
    NZEula.Add('        	in source code form or in unlocked coding or with comments.');
    NZEula.Add('');
    NZEula.Add('4.2	You will notify MYOB BankLink as soon as you become aware of any');
    NZEula.Add('        	infringement, suspected infringement or alleged infringement of');
    NZEula.Add('        	MYOB BankLink’s intellectual property rights in the Software.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('5	Warranties');
    NZEula.Add('');
    NZEula.Add('5.1	Except as otherwise agreed, MYOB BankLink is not obliged to support');
    NZEula.Add('        	the Software, whether by providing advice, training, error-correction,');
    NZEula.Add('        	modification, new releases or enhancements or otherwise.');
    NZEula.Add('');
    NZEula.Add('5.2	If you acquired this Software in New Zealand, to the extent');
    NZEula.Add('        	permitted by law, MYOB BankLink excludes and disclaims all and any');
    NZEula.Add('        	guarantees and/or warranties whether express, implied, statutory');
    NZEula.Add('        	or otherwise in respect of the Software and in particular, to the');
    NZEula.Add('        	extent that they are applicable, expressly excludes the provisions');
    NZEula.Add('        	of the New Zealand Consumer Guarantees Act 1993 pursuant to clause');
    NZEula.Add('        	43(2) thereof and the provisions of the New Zealand Sale of Goods');
    NZEula.Add('        	Act 1908 pursuant to clause 56 thereof. You confirm that you have');
    NZEula.Add('        	acquired the Software for business purposes.');
    NZEula.Add('');
    NZEula.Add('5.3	If you acquired this Software in Australia:');
    NZEula.Add('(a)	this Agreement does not exclude, restrict or modify:');
    NZEula.Add('	(i)	the application of any provision of the Australian Consumer Law');
    NZEula.Add('		("ACL") (whether applied as a law of the Commonwealth or any');
    NZEula.Add('		State or Territory of Australia);');
    NZEula.Add('	(ii)	the exercise of any right or remedy conferred by the ACL; or');
    NZEula.Add('	(iii)	the liability of MYOB BankLink for a failure to comply with any');
    NZEula.Add('		applicable consumer guarantees, where to do so would:');
    NZEula.Add('		A.	contravene the ACL; or');
    NZEula.Add('		B.	cause any part of this Agreement to be void.  ');
    NZEula.Add('(b)	to the extent permitted by law, MYOB BankLink excludes and disclaims all');
    NZEula.Add('	and any guarantees and/or warranties whether express, implied, statutory');
    NZEula.Add('	or otherwise in respect of the Software, except for any condition,');
    NZEula.Add('	warranty, guarantee, right or remedy under the ACL. Nothing in this clause 5');
    NZEula.Add('	excludes, restricts or modifies any condition, warranty, guarantee, right or');
    NZEula.Add('	remedy under the ACL.');
    NZEula.Add('');
    NZEula.Add('5.4	You acknowledge that MYOB BankLink does not warrant or promise that the');
    NZEula.Add('        	Software will meet your requirements and that you have solely exercised');
    NZEula.Add('        	and relied upon your own skill and judgment in determining whether the');
    NZEula.Add('        	Software meets your particular requirements, and have not relied on any');
    NZEula.Add('        	statement or representation by or on behalf of MYOB BankLink (unless');
    NZEula.Add('        	made fraudulently).');
    NZEula.Add('');
    NZEula.Add('5.5	MYOB BankLink is providing this Software to you "AS IS" and you');
    NZEula.Add('        	acknowledge that risk of loss or of damage to your computer system');
    NZEula.Add('        	or data at all times remains with you.');
    NZEula.Add(' ');
    NZEula.Add('5.6	MYOB BankLink does not warrant that:');
    NZEula.Add('');
    NZEula.Add('        	5.6.1	Any of the data provided by or on behalf of MYOB BankLink');
    NZEula.Add('		and received by you for use with the Software will be accurate');
    NZEula.Add('		or virus free;');
    NZEula.Add('');
    NZEula.Add('        	5.6.2	The Software will operate without interruption or errors; or');
    NZEula.Add('');
    NZEula.Add('        	5.6.3	That the Software will not affect the operation of other');
    NZEula.Add('		installed applications.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('6	Liability');
    NZEula.Add('');
    NZEula.Add('6.1	MYOB BankLink will not be liable to you for any loss or damage');
    NZEula.Add('        	(including, without limitation, consequential loss or damage)');
    NZEula.Add('        	suffered by you whether arising directly or indirectly from the');
    NZEula.Add('        	Use of the Software or any data provided by or on behalf of');
    NZEula.Add('        	MYOB BankLink under this Agreement or from any failure or omission');
    NZEula.Add('        	on the part of MYOB BankLink or otherwise.');
    NZEula.Add(' ');
    NZEula.Add('6.2	In no event will MYOB BankLink be liable for any remote, indirect,');
    NZEula.Add('        	consequential, punitive, special or incidental damages, including');
    NZEula.Add('        	without limitation, damages resulting from loss of any data, loss');
    NZEula.Add('        	of income or profits or business interruption, or cost of cover');
    NZEula.Add('        	whether based in contract, tort (including negligence), at law, in');
    NZEula.Add('        	equity, under statute or otherwise. This limitation will apply even if');
    NZEula.Add('        	MYOB BankLink has been advised of the possibility of such damages.');
    NZEula.Add('');
    NZEula.Add('6.3	Where the ACL applies (if you acquired this Software in Australia), then');
    NZEula.Add('        	the liability of MYOB BankLink for any loss arising as a result of or in ');
    NZEula.Add('        	relation to the supply by MYOB BankLink of the Software, including any');
    NZEula.Add('        	economic or consequential loss which may be sustained or incurred, shall');
    NZEula.Add('        	be limited to:');
    NZEula.Add('');
    NZEula.Add('        	6.3.1	The replacement of the Software or the supply of');
    NZEula.Add('                	equivalent Software;');
    NZEula.Add('');
    NZEula.Add('        	6.3.2	The repair of the Software;');
    NZEula.Add('');
    NZEula.Add('        	6.3.3	The payment of the cost of repairing or replacing the');
    NZEula.Add('                	Software or acquiring equivalent Software;');
    NZEula.Add('');
    NZEula.Add('        	6.3.4	The payment of the cost of having the Software replaced;');
    NZEula.Add('');
    NZEula.Add('        	6.3.5	The payment for the reduction in value of the Software; or');
    NZEula.Add('');
    NZEula.Add('        	6.3.6	The cost of the refund of the Software license fee, if');
    NZEula.Add('                	any, paid by you. However, nothing in this clause 6');
    NZEula.Add('                	excludes, restricts or modifies any condition, warranty,');
    NZEula.Add('                	guarantee, right or remedy under the Australian Consumer Law.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('7	Termination');
    NZEula.Add('');
    NZEula.Add('7.1	Without prejudice to any other rights, MYOB BankLink may terminate');
    NZEula.Add('        	this Agreement by written notice to you with immediate effect if you');
    NZEula.Add('        	fail to comply with the terms and conditions of this Agreement or');
    NZEula.Add('        	if you become bankrupt or insolvent (or suffer any similar');
    NZEula.Add('        	circumstances anywhere in the world).');
    NZEula.Add('');
    NZEula.Add('7.2	Upon termination for any reason:');
    NZEula.Add('');
    NZEula.Add('        	7.2.1	All rights granted to you under this Agreement shall');
    NZEula.Add('                	cease;');
    NZEula.Add('');
    NZEula.Add('        	7.2.2	You must cease all Use of the Software and any other');
    NZEula.Add('                	activities authorised by this Agreement; and');
    NZEula.Add('');
    NZEula.Add('        	7.2.3	You must immediately uninstall the Software and destroy');
    NZEula.Add('                	all copies of the Software in your possession and all its');
    NZEula.Add('                	component parts.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('8	Miscellaneous');
    NZEula.Add('');
    NZEula.Add('Entire Agreement');
    NZEula.Add('');
    NZEula.Add('8.1	This Agreement contains everything the parties have agreed in');
    NZEula.Add('        	relation to the subject matter it deals with. No party can rely on');
    NZEula.Add('        	an earlier written document or anything said or done by or on');
    NZEula.Add('        	behalf of another party before this agreement was executed.');
    NZEula.Add(' ');
    NZEula.Add('Variation');
    NZEula.Add('');
    NZEula.Add('8.2	No variation of this agreement will be of any force or effect');
    NZEula.Add('        	unless it is in writing and signed by each party to this');
    NZEula.Add('        	agreement.');
    NZEula.Add('');
    NZEula.Add('Privity of contract');
    NZEula.Add('');
    NZEula.Add('8.3	A party who is not you or MYOB BankLink shall have no right to enforce');
    NZEula.Add('        	any term under this Agreement whether under the Contracts (Privity) Act');
    NZEula.Add('        	1982 (if you acquired this Software in New Zealand) or any other local');
    NZEula.Add('        	Act or provision. This clause does not affect any right or remedy of');
    NZEula.Add('        	any person which exists, or is available, other than pursuant to the');
    NZEula.Add('        	relevant Act.');
    NZEula.Add('');
    NZEula.Add('Governing law');
    NZEula.Add('');
    NZEula.Add('8.4	If you acquired this Software in Australia, this Agreement and any');
    NZEula.Add('        	dispute or non-contractual obligation arising out of or in');
    NZEula.Add('        	connection with it shall be governed by and construed in');
    NZEula.Add('        	accordance with the laws of Victoria, and each party hereby');
    NZEula.Add('        	submits to the exclusive jurisdiction of the courts of Victoria over any');
    NZEula.Add('        	dispute arising out of or in connection with this Agreement.');
    NZEula.Add('');
    NZEula.Add('8.5	If you acquired this Software in New Zealand, this Agreement and');
    NZEula.Add('        	any dispute or non-contractual obligation arising out of or in');
    NZEula.Add('        	connection with it shall be governed by and construed in');
    NZEula.Add('        	accordance with the laws of New Zealand, and each party hereby');
    NZEula.Add('        	submits to the exclusive jurisdiction of the courts of New Zealand');
    NZEula.Add('        	over any dispute arising out of or in connection with this');
    NZEula.Add('        	Agreement.');
    NZEula.Add('');
    NZEula.Add('');
    NZEula.Add('9	Collection of Usage Information');
    NZEula.Add('');
    NZEula.Add('        	You agree that MYOB BankLink shall have the right to use, copy, store,');
    NZEula.Add('        	transfer, transmit, display and analyse any electronic data, information');
    NZEula.Add('        	or material, including the menus you select, the number of times each');
    NZEula.Add('        	is selected and the number of client files involved, which is sourced');
    NZEula.Add('        	by or through Use of the Software.');
    NZEula.Add('');
    NZEula.Add('        	You also agree that MYOB BankLink may collect, store, use and disclose');
    NZEula.Add('        	personal data (including personal data/information of you/your');
    NZEula.Add('        	clients) provided by you to MYOB BankLink (including, without');
    NZEula.Add('        	limitation your/your client''s name and user code). MYOB BankLink will');
    NZEula.Add('        	protect the information collected against unauthorised access, use');
    NZEula.Add('        	and disclosure and shall handle the same only in accordance with');
    NZEula.Add('        	MYOB BankLink''s privacy policy and by use of the Software you consent');
    NZEula.Add('        	to the collection, storage, use and disclosure of personal');
    NZEula.Add('        	information as set out in the relevant Privacy Policy. MYOB BankLink''s');
    NZEula.Add('        	privacy policy for New Zealand can be viewed at');
    NZEula.Add('        	http://www.banklink.co.nz/index.php/privacy, or for Australia at');
    NZEula.Add('        	http://www.banklink.com.au/index.php/privacy');
    NZEula.Add('');
    NZEula.Add('        	You warrant that you will not provide any personal information of');
    NZEula.Add('        	your clients to MYOB BankLink unless you:');
    NZEula.Add('        	(a)	have the prior consent of those clients to the disclosure;');
    NZEula.Add('                	and');
    NZEula.Add('        	(b)	have provided the clients with a copy of the relevant');
    NZEula.Add('                	MYOB BankLink Privacy Policy and that they have accepted and');
    NZEula.Add('                	consented to the collection, storage, use and disclosure');
    NZEula.Add('                	of personal information as set out in the relevant');
    NZEula.Add('                	Privacy Policy.');
    NZEula.Add('');
    NZEula.Add('        	You acknowledge, agree and further warrant that you will collect,');
    NZEula.Add('        	store, use and disclose the personal information of any individual');
    NZEula.Add('        	that may be provided to you by MYOB BankLink in accordance with the');
    NZEula.Add('        	MYOB BankLink Privacy Policy that is relevant to your jurisdiction.');

    mmoEULA.Lines := NZEula;
  finally
    FreeAndNil(NZEula);
  end;
end;

procedure TDlgLicense.SetAbout(Value: Boolean);
begin
  if Value then
  begin
    btnYes.Visible := False;
    lRead.Visible := False;
    lAccept.Visible := False;
    btnNo.Caption := '&OK';
  end;
end;

end.
