
#define Adding_GST_Amount_Tax_Invoice_and_Quantity	1
#define Adding_Notes	2
#define Adding_unpresented_items	3
#define Changing_column_widths_and_column_order	4
#define Chapter_1_Start_Here_	5
#define Chapter_2_BankLink_Notes_basics	6
#define Chapter_3_Processing_transactions	7
#define Chapter_4_Returning_Notes_files	8
#define Chapter_5_Reports	9
#define Chapter_6_Administration	10
#define Coding	11
#define Coding_by_Payee	12
#define Deleting_unpresented_items	13
#define Dissecting_transactions	14
#define Emailing_files_to_your_accountant	15
#define Emailing_from_BankLink_Notes	16
#define Getting_Help	17
#define Installing_BankLink_Notes	18
#define Opening_Files	19
#define Password_protecting_a_transaction_file	20
#define Print_Setup_Options	21
#define Producing_reports	22
#define Saving_files_and_abandoning_changes	23
#define Sorting_transactions	24
#define Updating_BankLink_Notes	25
#define Viewing_Bank_Accounts	26
#define Viewing_the_Transaction_Panel	27
