//------------------------------------------------------------------------------
//
// NotesHelp.inc
//
//------------------------------------------------------------------------------

const
  //Map IDs
  BKH_Adding_GST_Amount_Tax_Invoice_and_Quantity = 1;
  BKH_Adding_Notes = 2;
  BKH_Adding_unpresented_items = 3;
  BKH_Changing_column_widths_and_column_order = 4;
  BKH_Chapter_1_Start_Here_ = 5;
  BKH_Chapter_2_BankLink_Notes_basics = 6;
  BKH_Chapter_3_Processing_transactions = 7;
  BKH_Chapter_4_Returning_Notes_files = 8;
  BKH_Chapter_5_Reports = 9;
  BKH_Chapter_6_Administration = 10;
  BKH_Coding = 11;
  BKH_Coding_by_Payee = 12;
  BKH_Deleting_unpresented_items = 13;
  BKH_Dissecting_transactions = 14;
  BKH_Emailing_files_to_your_accountant = 15;
  BKH_Emailing_from_BankLink_Notes = 16;
  BKH_Getting_Help = 17;
  BKH_Installing_BankLink_Notes = 18;
  BKH_Opening_Files = 19;
  BKH_Password_protecting_a_transaction_file = 20;
  BKH_Print_Setup_Options = 21;
  BKH_Producing_reports = 22;
  BKH_Saving_files_and_abandoning_changes = 23;
  BKH_Sorting_transactions = 24;
  BKH_Updating_BankLink_Notes = 25;
  BKH_Viewing_Bank_Accounts = 26;
  BKH_Viewing_the_Transaction_Panel = 27;
  BKH_Editing_Superfund_details = 28;

var
  //filename of HTML help file
  HelpFileName : String = 'Notes_Guide.chm';

